vtex/utils/transform.ts

Turns out the querystring is also important for the final rendered image

fix: Duplicated images

---

vtex/utils/transform.ts
website/components/_Controls.tsx

Fix legacy filters to:
- keep current query on URL
- ignore empty mappings (ex.: `,c` should be only 1 mapping)
- allow root facet to be removing (thus returning to home)
Tests:
- Landing: https://deco-sites-embelleze-59yjtgj1w3qg.deno.dev/
- Search: https://deco-sites-embelleze-59yjtgj1w3qg.deno.dev/s?q=coloridos
- Departament: https://deco-sites-embelleze-59yjtgj1w3qg.deno.dev/Condicionador

Add missing VTEX catalog filters URL on categories and search

---

vtex/loaders/legacy/productList.ts

This PR aims to add support for [searching by productId](https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search) on the productList loader by adding 2 new props while keeping backward compatibility with the `ids` prop.
- Add `skus` and `productIds` props that will have the data for each type of search
- The `ids` prop fallbacks to the same behavior as `skus` to be backward compatible
- Add a helper function to avoid code duplication
- Test using `ids` or `skus`, should return a list of skus;
- Test using `productIds` should return a list of products;
- Other behaviors should stay the same.

Add support for searching by productId on productList loader

---

vnda/loaders/productList.ts
vnda/utils/transform.ts

When you call the VNDA search API, you receive a field called "tags." Today, in PDP, we must also receive this field like that, but VNDA has an error in this endpoint. So, I added the possibility to search by ID in the search endpoint (ProductList - Loader) and added the "tags" field in the "additionalProperty."

Product list transform vnda

---

compat/std/loaders/vtex/intelligentSearch/productDetailsPage.ts
compat/std/loaders/vtex/intelligentSearch/productList.ts
compat/std/loaders/vtex/intelligentSearch/productListingPage.ts
compat/std/loaders/vtex/intelligentSearch/suggestions.ts
compat/std/loaders/vtex/legacy/productDetailsPage.ts
compat/std/loaders/vtex/legacy/productList.ts
compat/std/loaders/vtex/legacy/productListingPage.ts
compat/std/loaders/vtex/legacy/relatedProductsLoader.ts
compat/std/loaders/vtex/legacy/suggestions.ts
compat/std/loaders/vtex/navbar.ts
compat/std/loaders/vtex/proxy.ts
compat/std/manifest.gen.ts
compat/std/mod.ts

This makes the admin showing only non-deprecated loaders when selecting loaders

Deprecate STD VTEX Loaders

---

vtex/utils/transform.ts

Sometimes `Image Label` and `Image Text` are different, also, `image text` may can be auto generated by vtex, so the property `alternateName` not even supply vtex migartions requirements.

feat: add Image Label Separated Of Image Text

---

commerce/mod.ts
compat/std/mod.ts
decohub/apps/shopify.ts
decohub/apps/vnda.ts
decohub/apps/vtex.ts
decohub/apps/wake.ts
decohub/manifest.gen.ts
shopify/mod.ts
vnda/mod.ts
vtex/mod.ts
wake/mod.ts

We currently have all commerce apps as dependencies of the site app. This causes the following dependency graph:
```
site.ts -> commerce.ts -> (vtex.ts | wake.ts | shopify.ts | vnda.ts)
```
The issue with this is that commerce.ts needs to know all commerce platforms. This PR makes it so we have the following dependency graph:
```
site.ts -> commerce.ts
vtex.ts
wake.ts
...
```
This causes the form the go from having a dedicated commerce prop inside site.ts, to the user having to install the app in the apps pannel
before: <img width="388" alt="image" src="https://github.com/deco-cx/apps/assets/1753396/01a4eacc-531a-485c-8325-28753353ec18">
after:

Move apps to decohub and add them as peer deps

---

vtex/loaders/intelligentSearch/productListingPage.ts

I made a modification to check if there is a current page being passed as a prop. Previously, we were only retrieving the "page" parameter from the URL, which worked only when the page was refreshed. The code was like this:
```
const page =
Math.min(
url.searchParams.get("page") ? Number(url.searchParams.get("page")) - currentPageoffset : 0,
VTEX_MAX_PAGES - currentPageoffset
);
```
Now, we have made the following change:
```
const page =
props.pageOffset ??
Math.min(
url.searchParams.get("page") ? Number(url.searchParams.get("page")) - currentPageoffset : 0,
VTEX_MAX_PAGES - currentPageoffset
);
```
Now, the code checks if the "pageOffset" property is present in the props. If it's present, it will use that value; otherwise, it will continue with the previous logic to obtain the page from …

Allow passing `pageOffSet` as props to IS productListingPage

---

vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/legacy/productListingPage.ts

When a url path does not contain `s` query and its not a page/category/department the return was a seach page with all products. To fix, I add the default vtex behavior, any path that is not a page its coverted by a search query, so when its a not valid query the return is a not found (if implemented by storefront) and when is, the return is the search return.
As said above, a path thats is no a page its a valid search term, the behavior is the same.

Fix: vtex search params IS/Legacy

---

commerce/sections/Seo/SeoPDP.tsx
commerce/sections/Seo/SeoPLP.tsx

When a search return no products, this shouldn't be tracked by search engines, só this meta its required.

Fix: include meta noindex on empty searchs and PDP

---

website/loaders/redirectsFromCsv.ts

this PR
**add:** the possiblity to provide a redirect type on csv, before its allways generated a temp redirect,
**fix:** the split function uses a simple comma as parameter, but when column has a comma as value its not working result in a wrong url `to` and wrong url `for`

Feat: add redirect type in redirectsFromCsv

---

analytics/components/Plausible.tsx
commerce/types.ts
website/components/Events.tsx
website/pages/Page.tsx

This PR changes how events are sent via plausible.
Currently, we are using only the server flags. This means we loose track of session flags (stored inside cookies). To keep track of dimensions stored inside cookies we need to manually trigger the pageView event or create the plausible tag on the client. 
I decided to go for the manual triggering since our frameowrk is server-based. Also, I copied from plausible the script part that raise pageview events on client-side navigation style

feat: Change plausible Events

---

algolia/utils/product.ts
utils/dataURI.ts
website/components/Analytics.tsx

This PR fixes some issues with the eventing API:
1. scriptAsDataURI throwing when non-latin characters were being used
2. Algolia now uses availability as sorting strategy and releaseDate as customRanking
3. Analytics allow not pushing to datalayer

feat: Algolia integration. Last steps

---

vtex/actions/cart/addItems.ts
vtex/actions/cart/getInstallment.ts
vtex/actions/cart/removeItemAttachment.ts
vtex/actions/cart/removeItems.ts
vtex/actions/cart/simulation.ts
vtex/actions/cart/updateAttachment.ts
vtex/actions/cart/updateCoupons.ts
vtex/actions/cart/updateItemAttachment.ts
vtex/actions/cart/updateItemPrice.ts
vtex/actions/cart/updateItems.ts
vtex/actions/cart/updateProfile.ts
vtex/actions/cart/updateUser.ts
vtex/loaders/cart.ts
vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/middleware.ts
vtex/mod.ts
vtex/utils/client.ts

Adds the default Sales channel config into vtex app config and forwards it into orderform. I think we don't need to forward it in search since we are already forwarding it via segment cookie

[vtex]: forward default sales channel

---

analytics/manifest.gen.ts
vtex/loaders/product/wishlist.ts
vtex/manifest.gen.ts
vtex/utils/extensions/mod.ts

This PR adds a new wishlist loader that returns a ProductListingPage, compatible to our usual search pages.
This new loader returns only the productID of items inside wishlist. To add other info required for rendering the wishlist page, this PR also adds a new "variants" toggle in our extension loader. This way we can compose these two loaders on the admin and fetch a full product from VTEX

feat: add wishlist loader

---

commerce/types.ts
vtex/utils/transform.ts

Some e-commerce sites use the BuyAndWin promotion. The only information about Buy and Win products is in GiftSkuIds, which returns us the Skus of products that are part of this promotion. Aware of this, we intend to retrieve this information with this PR, making it possible to retrieve this product and make it appear in the frontend. In VTEX IO this is done through a feature called Product Gifts.
Our loaders did not return this information, nor did it appear in the product Offers, which is where this information comes from, so it is intended that, with this PR, it will start to appear
vtex docs:
https://developers.vtex.com/docs/apps/vtex.product-gifts

feat (vtex): adding giftSkuIds available

---

vtex/loaders/legacy/productDetailsPage.ts
vtex/utils/transform.ts

Sometimes, the item will say it's a kit, but the kit items will not be returned by VTEX. 
This PR relax the loader boundary conditions so we do not throw on these cases

fix: missing skus

---

analytics/components/DecoAnalytics.tsx
commerce/types.ts
sourei/sections/Analytics/Sourei.tsx
website/components/Events.tsx
website/components/_Controls.tsx
website/pages/Page.tsx

This PR:
1. removes deco-flags event in favor of deco event, including flags and page
2. make sourei app to format numbers before adding to datalayer

feat: add deco event instead of flags

---

commerce/types.ts

Hello friends,
This PR corrects the items parameter of the select_promotion event so that it is optional, a necessary correction for correct operation in the frontend of typing in GA4 events
Also fixes the word 'coupon' in the add_shipping_info event
https://developers.google.com/gtagjs/reference/ga4-events?hl=pt-br

fix: optional items param select_promotion and coupon add_shipping_info

---

commerce/sections/Seo/SeoPLP.tsx
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/legacy/productListingPage.ts
vtex/utils/legacy.ts

From this change, it will be possible to decide whether the page number (PLPs) will be taken into account on indexing.
By default, the following pages would be indexed as the same page, that is, the same canonical tag would be generated for both:
`http://lojastorra.com.br/my-category?page=2`
`http://lojastorra.com.br/my-category?page=3`
However, when the user checks the `pgNumberIndexing` option, the above pages will be indexed separately.

feat: PLPs page numbers in canonical tags

---

vtex/utils/transform.ts

Submitting this pull request to ensure the preservation of the suggested retail price on products that undergo updates in their price table, as well as those featuring any enabled promotions on VTEX.
In the original product request on VTEX, there is a value for `PriceWithoutDiscount` that is currently typed but missing from the return provided by the product details loader. By adding this typed value as a Unit Price Specification for the suggested retail price, we can introduce a feature that displays the original price before any discounts from the price table, while still presenting the final price including all available promotions.
Example image taken from https://secure.zeedog.com.br/api/catalog_system/pub/products/search/?fq=productId:5052709

Enhancement: Inclusion of "Suggested Retail Price" in Product Details

---

website/components/_Controls.tsx

Adding Ctrl+X to the "go to code" activator will facilitate its use for ABNT keyboards.

Adding Control + X to activators

---

commerce/sections/Seo/SeoPDP.tsx
commerce/sections/Seo/SeoPLP.tsx

Canonical prop when set on SEO components will now be used instead of seo from loader.
It is not possible to currently override canonical from backend which can not be a desired effect on page.

Prefer canonical prop over response

---

vtex/actions/cart/getInstallment.ts
vtex/hooks/useCart.ts
vtex/utils/client.ts

The getCartInstallments doesn't return a orderform, so this dosen't has to be on enqueue function to not update context cart signal
this PR fix:  
- getCartInstallments action return type
- remove getCartInstallments from enqueue
ref: https://developers.vtex.com/docs/api-reference/checkout-api#get-/api/checkout/pub/orderForm/-orderFormId-/installments

fix: get cart installments shoudnt update cart context

---

vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/intelligentSearch/suggestions.ts
vtex/loaders/legacy/productDetailsPage.ts
vtex/loaders/legacy/productList.ts
vtex/loaders/legacy/productListingPage.ts

This pull request addresses an issue where currency code and locale info were hardcoded. This change replaces the hardcoded info with segment information sourced from VTEX App Configuration.

Fix: Removes hardcoded price currency code and locale info in Vtex Product Loaders

---

shopify/utils/transform.ts

Added the descriptionHtml field from the "ProductShopify" item into the AdditionalProperty variable of the Products. A follow up PR was made to the storefront repo as to omit the "descriptionHtml" property from the "useVariantSelector" component.

Add descriptionHtml to additionalProperty

---

vnda/loaders/productDetailsPage.ts
vnda/loaders/productList.ts
vnda/loaders/productListingPage.ts

If a product is created without variants, the VNDA api will return it as a [VNDAProductGroup](https://github.com/deco-cx/apps/blob/3325d94bc2c8261280a65d796b3f2e6cfc13df8a/vnda/utils/transform.ts#L19) with an empty `variants` array.
A product in this condition should be ignored by the product loaders because it is missing important data like price and availability. Besides, ignore it will prevent errors as expecting `variants` to have at least one variant.

Fix: VNDA - Ignore products with empty variants array

---

vtex/mod.ts

Description:
The sales channel selection in the VTEX app was previously restricted to the range of 1 to 5, preventing the selection of environments with sales channels greater than 5, as illustrated in the attached image.
Changes Made:
I have modified the property to a string type, enabling the selection of sales channels above 5.

 Allow Selection of Sales Channels Above 5 in VTEX App

---

website/sections/Rendering/Deferred.tsx

The Deferred section renders a button without an `aria-label` and it causes an accessibility fault in Lighthouse.
Adding an `aria-label` to the button, solves the problem.
---
Before:
---
After:

website/Deferred - Providing aria-label for Deferred section (button)

---

ai-assistants/chat/messages.ts
ai-assistants/mod.ts
compat/$live/loaders/state.ts
deno.json
platforms/kubernetes/actions/build.ts
platforms/kubernetes/actions/deployments/create.ts
platforms/kubernetes/actions/sites/create.ts
platforms/kubernetes/common/jobs.ts
platforms/kubernetes/loaders/siteState/get.ts
platforms/kubernetes/mod.ts
platforms/kubernetes/platform.ts
website/pages/Page.tsx
workflows/actions/start.ts

The major change here is how to default with default site state used when site is not created yet.
Previously:
The "defaultSiteState" passed as a prop of kubernetes app is being persistent on site creation.
The problem with that is because once the site state is saved, if the default site state changed, the new changes will be overwritten by the saved version, causing props not being updated with their new default values.
The ideal scenario is: Use site-specific value when persistent otherwise use default value, but since the default site state is being persisted, so there's no differentiation between default site state and specific site configuration.
Now:
Site state is merged with default when necessary but not persisted.

Do not persist default site state and use kubernetes watch (deno 1.39.2 fixes the watch bug)

---

website/sections/Rendering/Deferred.tsx

The "website" app has a component called "Deferred" that renders certain components based on the scroll or screen intersection. When we set it to render based on the scroll, the component executes several requests as we scroll until the first request finishes. To resolve this, I set the [`once`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#once) property in the eventlistener, which causes the event callback be executed only once.
Without once: 
With once true:

[Website] - Fix deferred firing unnecessary requests

---

admin/manifest.gen.ts
algolia/manifest.gen.ts
commerce/manifest.gen.ts
commerce/types.ts
commerce/utils/constants.ts
compat/$live/manifest.gen.ts
compat/std/manifest.gen.ts
decohub/manifest.gen.ts
linx/manifest.gen.ts
linx/utils/transform.ts
nuvemshop/manifest.gen.ts
nuvemshop/utils/transform.ts
platforms/kubernetes/manifest.gen.ts
power-reviews/manifest.gen.ts
shopify/manifest.gen.ts
shopify/utils/transform.ts
verified-reviews/manifest.gen.ts
vnda/loaders/productDetailsPageVideo.ts
vnda/manifest.gen.ts
vnda/utils/openapi/vnda.openapi.gen.ts
vnda/utils/openapi/vnda.openapi.json
vnda/utils/transform.ts
vtex/loaders/workflow/product.ts
vtex/manifest.gen.ts
vtex/utils/transform.ts
wake/manifest.gen.ts
wake/utils/transform.ts
website/manifest.gen.ts
workflows/manifest.gen.ts

Now you can find videos in the PDP on VNDA. They come from ImageObject.
This is the end-point: GET /api/v2/products/:productId/videos
I edit all loaders in deco to support this new key in ImageObject.
https://schema.org/ImageObject

feat: add video in PDP

---

wake/loaders/productListingPage.ts

O problema eram filtros duplicados do mesmo tipo, a página não retornava nada.
O objeto de filters era enviado assim:
``` [ { field: "Aroma", values: [ "Uva", "Vinho" ] } ]```
mudei para:
``` [ { field: "Aroma", values: [ "Uva"] }, { field: "Aroma", values: [ "Uva"] } ]```
passou a funcionar.

fix filter wake plp page

---

shopify/utils/transform.ts

if we use url.host, the url is constructed without the protocol, e.g. `localhost:8000/...` When using url.origin, the url is built with the protocol, e.g: `http://localhost:8000/...`

[Shopify] - Use origin instead of host to build product url

---

vnda/loaders/productListingPage.ts

This fix was to bring up the 404 pages in the VNDA app. 
Routes without "q" parameter don't work the search in vnda, so I fix it in this PR. 
Now you can search in pages like /example.

FIX/PLP (Search)

---

vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts

The changes in this PR brings fuzzy as a property of `productList` loader.
Currenty, `productList` loader [adds `fuzzy=auto` in search params](https://github.com/deco-cx/apps/blob/ae6207d086c29b2dad27b776a6ae78213dcb0b8e/vtex/loaders/intelligentSearch/productList.ts#L130), which in some cases, brings an wrong result.
`fuzzy=auto`
`fuzzy=0`

[VTEX] 'fuzzy' property added in productList loader

---

shopify/loaders/ProductListingPage.ts
shopify/utils/utils.ts

The current stock filter checks the "In stock" parameter value in the URL, but I can receive "In stock" for example, this PR fixes this by making the parameter value lowercase to avoid edge cases.

[Shopify] - Fix stock filter

---

website/handlers/redirect.ts

This PR fixes a bug where a "?" was added at the end of a url when redirected

[Website] - Fix redirect handler

---

decohub/manifest.gen.ts
website/mod.ts

A lot of stores were having problem with canonical, when you fill canonical at app "site", it overlaps other ones, affecting PDPs and PLPs.
In general, I do not think that canonical make senses in app "site".
Enjoying the movement, i am removing titleTemplate and descriptionTemplate from app "site", because both not receive any data to replace.

fix remove senseless props from app site

---

vtex/loaders/legacy/suggestions.ts
vtex/utils/fetchVTEX.ts

Entre aqui https://www.miess.com.br/ e veja a aba de network, agora na busca procure por cueca, funciona, agora se adicionar um espaço, dá 400
Isso acontece porque o espaço da url vira "+", e a api do legado não entende isso
https://www.miess.com.br/buscaautocomplete/?maxRows=12&productNameContains=cueca+&suggestionsStack=
Mas quando você troca o "+" por "%20", a busca funciona normalmente
https://www.miess.com.br/buscaautocomplete/?maxRows=12&productNameContains=cueca%20&suggestionsStack=
Por algum motivo quando "cueca " é adicionado aqui https://github.com/deco-cx/apps/blob/main/utils/http.ts#L136, o espaço vira "+" em vez de "%20"
Então eu substituo manualmente esse parâmetro encodando ele, em vez de usar o searchParams

Legacy autocomplete gives error if there is a space in the search

---

vtex/loaders/legacy/productListingPage.ts
vtex/utils/transform.ts

At category pages, we look for the current category to show all below in the three.
But, at search, collection, brand pages. The products are in different categories and object comes empty:
We could flat all categories here, but that would be weird, because we want to know the name of parent category. 
So, I liked @lui-dias purpose here: https://github.com/deco-cx/apps/pull/368. Bring categories separated:
Collection page before:
Collection page after:
At collection pages, the category link at filter should start with productClusterIds at map. Even at Vtex, it is necessary:
https://www.miess.com.br/velas/138?map=c,productClusterIds does not works.
https://www.miess.com.br/sex-shop/velas/138?map=c,c,productClusterIds works
This PR verify if request has a productClusterId at map and then …

flat categories to some type of pagetypes

---

analytics/components/DecoAnalytics.tsx
analytics/loaders/DecoAnalyticsScript.ts
website/components/Events.tsx

Today, we send events using html attributes, <script event-select-promotion="true"/>
We got a problem, because our matcher events could be "Product Page@..." and them, the problem:
``<script event-product page@something="true"``
I started to change to manual event, but it is necessary to do the logic to get historystate updates like push or replace, and popstate listener too.

change plausible pageview to manual at proxy

---

vtex/loaders/legacy/suggestions.ts

This PR brings back the `isVariantOf` object on the return of the VTEX legacy `suggestions` loader. 
It has the exact same shape as it once had in a [previous version of the repository](https://github.com/deco-cx/apps/blob/7ac0d59d52c51f6bdf2a966d6f4e3e12b09afb75/vtex/loaders/legacy/suggestions.ts#L60).
The `name` currently returned by the loader is the SKU name. 
This is fine in a lot of cases, but sometimes, the SKU name does not contain the product name, only a description of the variation. 
E.g.:
With `isVariantOf` containing the product name, stores can work around this issue, having access to the product name.

Feature: isvariantof on VTEX legacy suggestions

---

deno.json
website/handlers/fresh.ts
website/matchers/device.ts
website/mod.ts

More info at: https://github.com/deco-cx/community/issues/6

feat: Min threshold

---

vtex/utils/transform.ts

A Vtex não retorna uma promoção de preço fixo nos teasers, mesmo que a promoção esteja em destaque, em vez disso ela retorna no discountHighlight
Esse pr adiciona os itens do discountHighlight nos teasers

Add DiscountHighLight items in the teasers

---

website/handlers/fresh.ts
website/mod.ts

This PR turns async rendering a boolean and make cached loaders be able to not run for async loaders

feat: Improve async rendering

---

website/handlers/router.ts

If the site has a lot of redirects, ~80k like miess, it would take a long time to build the routes
This pr reduces this time
https://cdn.discordapp.com/attachments/1101246747604426885/1212419299814412309/2024-02-28_12-04-51.mkv?ex=65f1c476&is=65df4f76&hm=fe391f6f2369a4334358bdc161de7de51aafaf449f62f2cb94ad37a338843f7f&
Normal
https://miess-01.deco.site/?__d
With PR
https://deco-sites-miess-01--optimize-build-routes.deno.dev/?__d
Branch with PR
https://github.com/deco-sites/miess-01/tree/optimize-build-routes

perf: Optimize build routes

---

website/handlers/fresh.ts

Remove abort handler after fresh handler has return the getPage.
Fixes a potential memory leak.

Remove abort handler

---

decohub/apps/algolia.ts
decohub/apps/implementation.ts
decohub/apps/linx.ts
decohub/apps/shopify.ts
decohub/apps/sourei.ts
decohub/apps/typesense.ts
decohub/apps/vnda.ts
decohub/apps/wake.ts

The preview of some apps called the markdown component with await, and the markdown makes a fetch to get the content. So when importing apps into the decohub manifest, it was necessary to wait for the markdown to fetch.
This PR makes the component call the markdown only when it is rendered, so it avoids fetching when the apps are imported.

fix: Preview fetched when imported

---

vtex/loaders/legacy/productListingPage.ts

This is needed so that we can perform caching correctly in sites with pagination using the productListingPage legacy loader. Similar to what is done in the IntelligentSearch/ProductListingPage.ts.

Add search params to cachekey creation

---

linx-impulse/loaders/products/hotsite.ts
linx-impulse/loaders/products/productListingPage.ts
linx-impulse/manifest.gen.ts
linx-impulse/utils/transform.ts

This PR aims to separate the Hotsite loader from the linx impulse into a separate loader, previously it was next to the PLP loader, the PR also fixes an error that the value sanitize function did a stringify in the arrays, the correct thing would be to take the first value , e.g: 
```js
Brand: ["Penalty"] // '["Penalty"]' ❌
Brand: ["Penalty"] // "Penalty"     ✅
```
https://deco-sites-clovis.deno.dev/

refactor(linx-impulse): Hotsite loader

---

website/loaders/fonts/googleFonts.ts

This PR fixes an error occurring in the Google font loader, where if a user created two font variations with the same weight or the variations were not ordered correctly, it would cause an error in the request. I also made it easier to view variants by adding a @­title in the FontVariation interface
This is when the error occurs
Before adding title
After adding title

fix(google-fonts): Sort and filter duplicated font variations

---

vtex/utils/transform.ts

This PR aims to fix the `fmap` query param in VTEX legacy (catalog) loaders, when it's behavior is set to `static`. In this behavior, all the facets are kept when the user selects one. For example, in the `dynamic` behavior, when setting the "Cor" facet being "Azul", the resulting search facets will remove all the "Cor" options and only show "Azul". But with the `static` behavior, all of them are shown still, enabling the user to select both "Azul" and "Amarelo" options of "Cor", resulting in a union of them.
The problem is, after the PR #392, the `fmap` query param (`static` behavior uses it to keep track of the initial facet) became broken: when inside a category, the "Azul" facet option should have `fmap=c` in it's URL (that's how it worked before the mentioned PR), but the URL …

Fix: Wrong facet map in VTEX legacy loaders with `static` behavior

---

commerce/sections/Seo/SeoPLP.tsx
commerce/sections/Seo/SeoPLPV2.tsx
vtex/loaders/legacy/productDetailsPage.ts
vtex/utils/legacy.ts
website/components/Seo.tsx

In this pr I add 
```js
<meta name="robots" content="index, follow">
```
in all pages who don't receive "noIndexing prop" and add use cases to don't follow in PLP and PDP
https://www.embelleze.com/Neutralizante/TRATAMENTO/1568?map=c%2Cc%2CproductClusterIds
https://app.liveseo.com.br/projeto/CB566/task/8439/128563/preview?key=iXYXeK8m2S9x5Bhe

[ SEO | VTEX ] Add meta robots in SEO PLP and SEO PDP

---

shopify/loaders/proxy.ts
shopify/utils/cart.ts
website/handlers/proxy.ts

First
Shopify now asks for digest_cookie at checkout for stores that have password.
Second
We were replacing all cookies at proxy level and it brokes checkout.

fix custom headers if it is cookie

---

utils/shortHash.ts
website/loaders/fonts/googleFonts.ts

Create a cachekey for googlefonts loader based upon fonts (GoogleFonts[]) property.

Make googlefonts loader cacheable.

---

website/handlers/router.ts

Avoid router to match /frsh routes (and accept 200 responses)

Avoid frsh routes

---

vtex/loaders/product/extend.ts

This PR solves de TypeError on the VariantsExt function
When updating apps to version 0.36.14, the wish list stops working and returns this error:
If you add a check or optional chaining in line 81 of this extend.ts (“apps/vtex/loaders/product/extend.ts”), the wish list works again

fix: prevent TypeError in variantsExt function

---

commerce/sections/Seo/SeoPDP.tsx
commerce/sections/Seo/SeoPDPV2.tsx
commerce/sections/Seo/SeoPLP.tsx
commerce/sections/Seo/SeoPLPV2.tsx
website/sections/Seo/SeoV2.tsx

This PR adjusts the SEO components to include the "noIndexing" property when disabling page indexing via the Deco CMS. Currently, the behavior is to maintain indexing if the page has data in the JSON LD, even if the user has selected in the CMS that they do not want to index the page. With the fix, the user's choice in the admin becomes the priority, so the page will not be indexed, even if it has data in the JSON LD.
Old behavior with indexing disabled in the Deco admin:
Behavior after the fix:

Fix: Consider the "noIndexing" property when disabling page indexing

---

utils/normalize.ts

Quotes on UTM query parameters breaks VTEX API.

Remove quotes from utm

---

website/handlers/fresh.ts

This allow any subsequent calls to resolve to have the same hooks as the first one called at page level. This allows matchers to be evaluated without time restrictions.

Add propagate options

---

website/handlers/fresh.ts

Don't remove abort ctrl so deno can do its cleanup

---

algolia/sections/Analytics/Algolia.tsx
analytics/components/DecoAnalytics.tsx
analytics/loaders/DecoAnalyticsScript.ts
htmx/hooks/useScript.ts
htmx/sections/htmx.tsx
sourei/sections/Analytics/Sourei.tsx
utils/dataURI.ts
utils/lru.ts
utils/useScript.ts
vtex/components/VTEXPortalDataLayerCompatibility.tsx
vtex/sections/Analytics/Vtex.tsx
website/components/Analytics.tsx
website/components/Events.tsx
website/components/_Controls.tsx
website/sections/Rendering/Deferred.tsx

This PR adds a new hook called useScript. 
This hook allows you to write inline scrips, much like `scriptAsDataURI` function, but without having to deal with minification. Also, this PR drops support for `scriptAsDataURI` function since I've discovered base64 increases up to 30% final uris and encodeURIComponent should do the job.

feat: inline scripts support

---

magento/actions/cart/addCoupon.ts
magento/actions/cart/addItem.ts
magento/actions/cart/removeCoupon.ts
magento/actions/cart/removeItem.ts
magento/actions/cart/setSimulation.ts
magento/actions/cart/updateItem.ts
magento/loaders/cart.ts
magento/mod.ts
magento/utils/cart.ts

feat: adding option to create card to add item

---

compat/std/loaders/x/redirects.ts
website/handlers/redirect.ts
website/loaders/redirects.ts
website/loaders/redirectsFromCsv.ts

Greetings,
This PR adds the option for the user to choose whether they want to keep the parameters in the redirect or not.
The functionality was changed to add the feature for files loaded via CSV and through the dashboard.
One issue that is occurring is that in the admin panel, the option, although functional, is not being saved. I would need some assistance or correction for this.
* In this image, I demonstrate that despite being active, if I make it public, it will work. However, after refreshing the page, it remains functional but the active status is not retained.
** The parameter combination was initially starting as true by default. In this PR, I've changed it to false because "from" leads to "to," and if the user wishes "from" to lead to "to" with parameters added, they can enable …

feat: choose whether to concatenate URL parameters in the redirect.

---

magento/loaders/product/detailsPageGQL.ts
magento/utils/clientGraphql/types.ts

fix(magento): pdp in uses only gql

---

htmx/sections/htmx.tsx

The HTMX script was trying to define the "hx-ext" attribute in the "body" so that the extensions would be available throughout the site, but as the script is in the <head> the body does not exist yet, returning null and giving an error when adding the attribute, now the script checks if the DOM is already loaded to add the extensions, and if not, it adds an onload listener to the window to be added as soon as possible

fix: set attributes after DOM loads

---

ai-assistants/mod.ts

Removendo esse erro do admin.
O id que ele se refere no erro existe sim na nossa openAI, mas nao tem nenhum assistente no admin configurado, logo teoricamente esse assistant_id existe, mas na verdade nao existe. E quem solta esse erro é a funcao de retrieve. Entao parece que checando antes se existe algum assistente configurado resolve o problema. Acho que isso resolve o erro sem quebrar o funcionamento anterior...

fix: remove ai assistant error insuportavel

---

linx/loaders/proxy.ts
linx/utils/headers.ts
utils/http.ts
website/handlers/proxy.ts

linx(fix + debug): Exclude headers that cause the API to fail on different infra + CURL logs for proxy and outbound requests.

---

wake/actions/cart/updateItemQuantity.ts

Ao aumentar a quantidade no minicart o produto era removido e adicionado novamente, alterando a ordem dos produtos 
Esse PR corrige esse comportamento

fix: Prevent the cart from resorting when the quantity is updated

---

website/components/Image.tsx

In the previous PR I was not transforming the image if the feature was not enabled. This transforms the image anyways but add a log so we can catch. This is better because it allow us to have errors and not nuke the store in production

change: previous commit

---

commerce/loaders/product/extensions/detailsPage.ts
commerce/loaders/product/extensions/list.ts
commerce/loaders/product/extensions/listingPage.ts
vtex/loaders/collections/list.ts
vtex/loaders/product/extend.ts
vtex/loaders/product/extensions/detailsPage.ts
vtex/loaders/product/extensions/list.ts
vtex/loaders/product/extensions/listingPage.ts
vtex/loaders/product/extensions/suggestions.ts
vtex/loaders/product/wishlist.ts

This PR adds export const cache = 'stale-while-revalidate' to enable cache async render sections

feat(vtex, commerce): add stale-while-revalidate for vtex extension loaders

---

commerce/loaders/product/extensions/detailsPage.ts
commerce/loaders/product/extensions/listingPage.ts
compat/$live/loaders/state.ts
deno.json
vtex/loaders/product/extend.ts
vtex/loaders/product/extensions/detailsPage.ts
vtex/loaders/product/extensions/listingPage.ts

Add cache=no-cache to allow sections that depend on these loaders to be cached when rendered by /deco/render. related to https://github.com/deco-cx/deco/pull/788

feat(vtex, commerce): add no cache for product extension loaders

---

anthropic/actions/stream.ts
deno.json

Disable stream chunk decoding while reading from stream

fix: disable anthropic stream chunk decoding

---

commerce/loaders/navbar.ts
compat/std/loaders/vtex/navbar.ts
vtex/loaders/navbar.ts

Adds `cache = 'no-cache'` on `loaders/navbar.ts`

feat(vtex, commerce): add cache=no-cache for navbar loaders

---

linx/loaders/auction/detailsPage.ts

from `//leilao/12345` (breaks) -> `/leilao/12345`

fix: remove first slash of the pathname on auction detail

---

website/handlers/proxy.ts
website/loaders/asset.ts

Streams on deno increases memory usage.
We did some tests considering a program that uses a stream to process a proxied fetch and found a high memory usage both on 1.44.4 and 1.46.1:
```
matheusgr@xpto % deno run -A stats.ts 1.46.1-stream.txt 
Mean: 155601.2
Median: 156768
25th Percentile: 147616
50th Percentile (Median): 156768
75th Percentile: 167136
Standard Deviation: 17387.814910448065
95% Confidence Interval: [152490.12517228883, 158712.2748277112]
```
Non-streamed version (read all body before processing and send it):
```
matheusgr@xpto % deno run -A stats.ts 1.46.1-copy.txt  
Mean: 73920.8
Median: 74216
25th Percentile: 64848
50th Percentile (Median): 74216
75th Percentile: 84032
Standard Deviation: 15291.060129805699
95% Confidence Interval: [71184.88220332093, 76656.71779667908] …
```

Avoid stream and clone

---

blog/loaders/GetCategories.ts
blog/manifest.gen.ts
blog/utils/handlePosts.ts

This PR fix the blogpost listing order -> now, the order works properly;
And adds a new loader to get all blogpost categories

feat(blog): get all categories

---

vtex/hooks/context.ts
website/handlers/fresh.ts
website/handlers/router.ts

Avoid ctx binding

---

vtex/hooks/context.ts

HOTFIX: Code may use signal even on server side. Avoid break signal compatibility by setting a null value.

Keep signal prop accessible on vtex context on serverside

---

website/handlers/router.ts

Allow users to specify search params on route path to be used by URLPattern.
URLPattern already support search params, we are not using it so far, but we have now included. Users needs to specify following URLPattern [documentation](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern).
Example usecase in the linked issue.
- Issue: [#823 ](https://github.com/deco-cx/apps/issues/823)

Allow users to specify search params on route path

---

anthropic/actions/code.ts
anthropic/actions/invoke.ts
anthropic/actions/stream.ts
anthropic/deps.ts
anthropic/manifest.gen.ts
anthropic/utils.ts
blog/sections/Template.tsx

Create `invoke` action for non-streaming anthropic api calls with tool use support.

feat: anthropic invoke with function call

---

records/scripts/pullProd.ts

fix(records): scripts pull prod to use @libsql/client/node

---

shopify/loaders/ProductListingPage.ts

This PR solves the problem of the shopify loaders/productListingPage not varying the cacheKey based on the filters querystring that comes from the URL
- fixes: [#838](https://github.com/deco-cx/apps/issues/838)
> https://sites-issue-838-g--env.decocdn.com/men?sort=price-ascending&page=0

fix(shopify): add `filters` to productListingPage cacheKey 

---

vtex/loaders/proxy.ts
wake/loaders/productListingPage.ts
website/handlers/proxy.ts

vtex proxy: replace only text/html and add referer for AviseMe path

---

shopify/utils/transform.ts
vtex/utils/transform.ts

I don't think we should broke if the skuId in queryParams doesn't exists on the list, just get the first one.

tavano fix wrong sku

---

decohub/components/Markdown.tsx

Dynamic import deno gfm
- Issue: [#887](https://github.com/deco-cx/apps/issues/887)
Before/After

Dynamic import gfm

---

vnda/actions/cart/addItems.ts
vnda/manifest.gen.ts
vnda/utils/openapi/vnda.openapi.gen.ts
vnda/utils/openapi/vnda.openapi.json

This PR introduces a new action that allows for bulk addition of items to the cart, enhancing performance and user experience. This feature is especially useful for "Buy Together" functionalities commonly utilized in e-commerce platforms.
- Created an asynchronous `action` function that accepts a list of items to be added to the cart.
- Implemented error handling for missing cart cookies, returning a `400` HTTP error if the cookie is absent.
- Enhanced the payload structure to match the OpenAPI standards for bulk item addition, as specified in the VNDA documentation: [VNDA API Documentation](https://developers.vnda.com.br/reference/post-api-v2-carts-cart_id-items-bulk).
- Introduced a new loader to optimize the retrieval of cart data after items are added.
- **Input**: The action takes a …

[VNDA] Feat: create addItems action

---

utils/http.ts

Some httpclients may need empty segments, specially at the end of the URL.

Opt keep empty paths on http client

---

vtex/loaders/legacy/relatedProductsLoader.ts

Brief Description of Changes:
This pull request enhances the relatedProductsLoader function by improving its error handling mechanism. Previously, the loader used Promise.all to fetch related products in batches, which caused the entire loader to fail if any single productList call rejected due to an error (e.g., API failure or network issue). This behavior led to unhandled promise rejections and potential application instability.
To address this issue, the following changes have been made:
Replaced Promise.all with Promise.allSettled: This allows all promises to complete regardless of individual failures. It prevents the loader from rejecting entirely when a single promise fails.
Result Handling: The loader now filters the fulfilled promises to collect successful results and handles …

fix: change related products promise type

---

vtex/loaders/legacy/relatedProductsLoader.ts

Before #878, relatedProducts didn't thrown exception if all products fail.
We are reverting it due to:
- changing established behavior
- related products isn't a critical loader
We may later improve that behavior.

Avoid throw on related legacy products when all Promise fails

---

posthog/components/PostHog.tsx

Post hog needs the "$current_url": window.location.href to properly register a pageview. Also, it doesn't need to auto capture page views since we already do that programatically.

Fix posthog autocapture

---

shopify/loaders/proxy.ts
shopify/mod.ts

This PR implements the addition of a new property, `publicUrl`, to the Shopify proxy loader. The goal is to prevent issues with registered domains that have redirects, ensuring that the correct URLs are used during requests and avoiding bugs related to proxies.
- **Updated `buildProxyRoutes` function**: 
- The function now accepts a new parameter, `publicUrl`, which can be provided through the context.
- If `publicUrl` is present, it will be used to construct the proxy URL; otherwise, the default Shopify store domain (`https://${storeName}.myshopify.com`) will be used.
```javascript
const urlToUse = publicUrl ? 
new URL(publicUrl.startsWith("http") ? publicUrl : `https://${publicUrl}`) :
new URL(`https://${storeName}.myshopify.com`);
```
- **Hostname Validation**: 
- Logic was added to …

feat(shopify): adding public Url to be proxied on shopify

---

vtex/actions/cart/updateItems.ts

This new props prevents VTEX cart from splitting it's items when increasing their quantity

chore: add new update cart prop

---

vtex/utils/transform.ts

The function that handles the image url mapping was breaking whenever receiving an undefined value, this PR adds a validation for it
Before fix: https://www.loom.com/share/659c9eb50d21433da77368c76d934b1e
After fix: https://www.loom.com/share/edc6d6eeb6cd4201bad5875bdf220597

chore: handle undefined images

---

shopify/loaders/proxy.ts

Allow proxy on shopify to replace content.
Example:
- some shopify JS may refer the internal domain (site.myshopify.com) that provides an graphql API. This API is accessible only thought a server due to missing CORS headers, so it need a proxy to access it. We can replace this domain with our server so it has a way to access it.

add replace on shopify

---

vtex/loaders/intelligentSearch/productListingPage.ts

Hi guys, I added a new prop to send the price filter in facets. I identified an issue where, when applying the price filter, some filters are displayed even though they don't have corresponding products.
Here's a video with the demonstration.
Video: https://github.com/user-attachments/assets/1431e0dc-890d-40d4-8a0d-ac17326d2a1f

fix: include filter price in facets

---

shopify/actions/user/signIn.ts
shopify/actions/user/signUp.ts
shopify/loaders/proxy.ts
shopify/manifest.gen.ts
shopify/utils/storefront/queries.ts

This PR is a complement to [PR #890](https://github.com/deco-cx/apps/pull/890), where I implemented the user hook and the signIn action.
- **signUp Action**: I am now implementing the signUp action, which will allow users to complete the registration flow directly from the frontend, without the need for a proxy to Shopify.
Return:
When the email has already been taken:
This update aims to enhance the user experience by streamlining the login and registration processes.

[Shopify] Feat: adds signUp action

---

vtex/actions/orders/cancel.ts
vtex/utils/client.ts

- **Interface Update**: Added the `requestedByUser` property to the `Props` interface.
Reference: https://developers.vtex.com/docs/guides/order-canceling-improvements
```markdown
```typescript
interface Props {
orderId: string;
reason: string;
requestedByUser: boolean; // New property added
}
```
- **Action Function Update**: Updated the action function to include the `requestedByUser` in the request body.
```typescript
async function action(props: Props) {
const { orderId, reason, requestedByUser } = props;
const response = await vcsDeprecated
["POST /api/oms/pvt/orders/:orderId/cancel"](
{ orderId },
{
body: { reason, requestedByUser }, // New property included
headers: { cookie },
}
);
}
```
- **VTEXCommerceStable Interface**: Added `requestedByUser` to the `VTEXCommerceStable` …
```

feat: add new prop and body item to cancel order action

---

vtex/hooks/useCart.ts

Removed window from this hook to support Deno 2.
The window used in this hook in globalThis has been [discontinued](https://docs.deno.com/runtime/reference/migration_guide/#:~:text=Use%20globalThis%20instead.). The [storefront template](https://github.com/deco-sites/storefront/blob/36c5dc2fa759426dc7ebde1f47cc6cf55226a037/sdk/cart/vtex/loader.ts#L24) uses this hook here in vtex stores.

Removed window from this hook to support Deno 2.

---

admin/widgets.ts

This PR introduces a new widget type to the Deco.cx CMS: **DateTime**, which enables the selection and display of both date and time.
- **Type**: `DateTime` (format `string`)
With this addition, users can easily include date and time fields in their content structures, providing greater flexibility for managing date-related content.

feat: add date-time type on widgets

---

shopify/utils/storefront/storefront.graphql.gen.ts
vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/intelligentSearch/suggestions.ts
vtex/loaders/intelligentSearch/topsearches.ts
vtex/loaders/logistics/getSalesChannelById.ts
vtex/loaders/logistics/listSalesChannelById.ts
vtex/manifest.gen.ts
vtex/utils/intelligentSearch.ts
vtex/utils/openapi/vcs.openapi.gen.ts
vtex/utils/types.ts

use the dynamic locale prop

---

konfidency/actions/submitReviews.ts
konfidency/manifest.gen.ts
konfidency/utils/client.ts
konfidency/utils/types.ts

Creating an action to evaluate the product 
Provide a brief description of the changes or improvements you are proposing in this pull request.
Based on the Konfidency API, an action was developed to send the product review using the product's sku as a reference, and based on typing the [documentation](https://docs.konfidency.com.br/docs/konfidency-comments/api/reference/#par%C3%A2metros-de-url-1) 
Link to the relevant issue this pull request addresses:
The customer needs to evaluate the products at [Vizzent](https://www.vizzent.com.br/sandalia-de-festa-e-salto-alto-via-marte-bege-149-012-04-np-machiato/p?skuId=67520)
[Demo](https://www.loom.com/share/744a02a13f0d4c8b89d2b595c0283a24?sid=6207e79e-3165-430d-a9a9-1ed2d9852783)

feat: submit review

---

konfidency/loaders/productDetailsPage.ts
konfidency/utils/client.ts

Solution to the problem with intermittent responses to Konfidency reviews on PDP
Provide a brief description of the changes or improvements you are proposing in this pull request.
As analyzed in the Konfidency documentation, we found a problem in the request on [product evaluation endPoint], where previously the sortField and sortOrder values ​​were not passed, resulting in a lack of evaluation data
https://www.loom.com/share/602525ae12d94b239a2d2cad7adf08ab?sid=4725c5cd-f9de-44ca-a4a8-a9202efb983e

fix: implementation of sortField and sortOrder fields

---

blog/loaders/BlogRelatedPosts.ts
blog/manifest.gen.ts
blog/utils/handlePosts.ts

This PR was made to add the option to search related posts.
The search is carried out according to the category/categories of the post.
An optional "excludeSlug" prop was also added to exclude the current post from the return list.
Example:

feat(blog): add related posts

---

blog/types.ts
blog/utils/records.ts

This PR aims to add the unique id of the blog post.
As the post can be 100% edited (including the slug), we added this id to have a unique identifier.
Aiming at a scenario in which we save comments using the post_slug in the comments table, if there were any changes to the slug due to an error or anything else, we would lose all data registered in the system due to this change.

feat(blog): expose unique identifier

---

konfidency/actions/submitReviews.ts
konfidency/loaders/productDetailsPage.ts
konfidency/manifest.gen.ts
konfidency/utils/client.ts
konfidency/utils/types.ts
verified-reviews/utils/client.ts

The Verified reviews have some custom atributes for some clients. Some clients use date_ASC" others use "date_asc. The PR's suggestion would be to leave a toggle in the admin, so when the client is one that uses the lowercase sorting options, simply activate the toggle.
> https://www.loom.com/share/cdd5dadf33304f70a3d6fe3e66f4c736?sid=b2bc9490-ade6-4614-b10b-c43bec0b483c
> https://sites-oficina-reserva--feat-reviews.decocdn.com/camiseta-pima-premium-gola-c-preta-0079110040/p?skuId=8965

fix: reviews ordenation

---

website/loaders/pages.ts

Now you can make a partial go-live and proxy the other pages. 
https://sites-fila-store--proxy-pages.decocdn.com/sale
https://sites-fila-store--proxy-pages.decocdn.com/sale?rdc=true
Essa imagem representa uma página de categoria na deco (Isso é porque a variant não está cadastrada com um always) 
https://www.loom.com/share/6d10fedeaca345f0ac06d03edde2b632?sid=a468d6cc-f8af-41cc-956d-138822ceecc3

priorization pages

---

verified-reviews/utils/client.ts
vtex/actions/analytics/sendEvent.ts
vtex/loaders/promotion/getPromotionById.ts
vtex/utils/openapi/vcs.openapi.json
vtex/utils/types.ts

An empty array as type is converted to "Items: []" which is an invalid json.
By setting as a {} object, it will accept any empty object which is valid to represent anything really (but is not interpreted by a rjsf).
- Issue: https://github.com/deco-cx/apps/issues/990

Fix empty cart type

---

vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/intelligentSearch/suggestions.ts
vtex/loaders/legacy/productDetailsPage.ts
vtex/loaders/legacy/productListingPage.ts
vtex/utils/pickAndOmit.ts
vtex/utils/transform.ts
vtex/utils/types.ts

[Discord Discussion](https://discord.com/channels/985687648595243068/1310591630608302150)
https://admin.deco.cx/sites/oficina-reserva/spaces/dashboard?env=fix%2Fsku-specs
- Legacy PLP / PDP
- Intelligent Search PLP / PDP
In the process of transforming DecoCX product data into the **schema.org** format, some important product attributes are being lost. These attributes might be necessary for specific use cases in the storefront, leading to limitations in the available data.  
To address this issue, we propose adding an **"Advanced Config"** property to some loaders. This property would include an attribute named **`originalAttributesToInclude`**, which would be an array of strings representing the key names of the original attributes to retain.  
These specified attributes would then be …

Feat: Enhance Product Data Handling in DecoCX Schema.org Transformation

---

vtex/actions/masterdata/updateDocument.ts
vtex/manifest.gen.ts
vtex/utils/openapi/vcs.openapi.gen.ts
vtex/utils/openapi/vcs.openapi.json

Feat(VTEX): Implement masterdata update document API

---

shopify/utils/transform.ts

**Pull Request Description:**
This Pull Request adds the `productType` value returned by Shopify to the product's additional properties. The change ensures that the `productType`, which was previously not being considered, is now correctly included. The implementation details are as follows:
1. The `productType` value is extracted from the `product` object returned by Shopify.
2. A new `PropertyValue` object is created with the name `"productType"`, and its value is set to the `productType` value from the product.
3. This new `PropertyValue` is concatenated with other additional properties, such as the product description and metafields, within the `additionalProperty` array.
Example:
**Context:**
In the current repository, there is some confusion with the `type` object returned by the …

[Shopify]: add productType to product transformation

---

vtex/loaders/legacy/productDetailsPage.ts
vtex/utils/types.ts

[Feat] - VTEX - Legacy

---

commerce/types.ts
vtex/loaders/user.ts

Add vtex user telephone to user loader and telephone type to Person

[VTEX] feat: add vtex telephone

---

htmx/sections/Deferred.tsx
streamshop/sections/Carousel.tsx
streamshop/sections/Stories.tsx
utils/components/Slider.tsx
vtex/preview/Preview.tsx
website/components/Image.tsx
website/components/Picture.tsx
website/components/_seo/Google.tsx
website/pages/Page.tsx
website/sections/Rendering/Deferred.tsx

Fix lint and checks

---

commerce/sections/Seo/SeoPDPV2.tsx
commerce/sections/Seo/SeoPLPV2.tsx
vtex/loaders/intelligentSearch/productList.ts
website/loaders/secret.ts

This PR refactors the SEO PLP and PDP sections to avoid sending the structured data for the customers as it's only useful for crawlers and bots.
This changes can decrease significantly the Document size on product listing pages with many products, specifications and variants
https://github.com/user-attachments/assets/22cf7a6c-c523-49f4-b2a9-681fe9d50f97

Refactor(SEO): show structured data only to bots/crawlers

---

website/components/Image.tsx

The `Image` component serves as a wrapper that optimizes image URLs for each e-commerce platform while leveraging the optimized Deco CDN. However, the current `srcSet` generation is limited because it only considers two factors, preventing the generation of intermediate image sizes.
Since modifying the existing `srcSet` logic could introduce breaking changes across all stores, a more flexible approach would be to allow an optional `srcSet` prop, enabling customization without altering the default behavior.
Introduce an optional `srcSet` prop to the `Image` component, allowing developers to define custom breakpoints while maintaining backward compatibility.

Improve srcSet flexibility in the Image component

---

vtex/loaders/legacy/productListingPage.ts

[Fix] - Remove the override from props in fq

---

website/components/_seo/Preview.tsx

Window is discontinued in deno 2. Developers running the project in localhost has error while preview the SEO

Remove window in SEO Preview

---

wake/loaders/proxy.ts

This PR fix the extraPathsToProxyh format on wake integration

[Wake] fix: extra paths proxy

---

vidu/actions/imageToVideo.ts
vidu/actions/referenceToVideo.ts
vidu/actions/startEndToVideo.ts
vidu/actions/textToVideo.ts
vidu/manifest.gen.ts
vidu/mod.ts

* Rearranged the order of actions in the manifest for consistency.
* Updated video action functions to accept `req` parameter instead of `_req` and retrieve `installId` from the request URL.
* Ensured `installId` is included in the preview URLs for better traceability in video generation responses.

refactor: reorganize manifest and update video action parameters

---

vidu/actions/imageToVideo.ts
vidu/actions/referenceToVideo.ts
vidu/actions/startEndToVideo.ts
vidu/actions/textToVideo.ts
vidu/utils.ts

* Introduced `getInstallId` function in `utils.ts` to extract the install ID from a specific URL pathname format.
* Updated video action files to utilize the new utility function for retrieving install ID, improving code consistency and readability.

feat: add utility function to extract install ID from URL

---

1001fx/actions/audio2video.ts

- Updated the upload function to fetch the video data as an ArrayBuffer and convert it to a Buffer for uploading.
- Changed the content type for the upload request from JSON to octet-stream to accommodate binary data.
- Fixed the status code in the error response from 500 to 5 for consistency.
These changes improve the handling of video uploads and error reporting in the audio-to-video conversion process.
> Provide a link …

Refactor audio upload process in audio2video action

---

website/loaders/fonts/googleFonts.ts

When google fonts request throw an error, a page can't be resolved. The fix consists into catch the error and allow page render.

fix: catch font error at googleFonts loader

---

website/loaders/asset.ts
website/loaders/image.ts
website/loaders/whitelistAssets.ts
website/loaders/whitelistDomains.ts
website/manifest.gen.ts
website/mod.ts

- Enhanced control over resource proxying via `/image.ts` and `/assets.ts` routes.
- Added `disableProxy` (boolean) to disable proxying entirely for a site.
- Added `whitelistURLs` (array of URL/domain patterns) to limit which resources can be proxied.
- If `whitelistURLs` is omitted and proxying is enabled, all sources will be allowed.
- Changes to the whitelist may take up to 120 seconds to propagate.
These additions allow more flexible and fine-grained control over external image and font proxy behavior on a per-deployment basis (you may test locally or using an env var).

Whitelist domain for assets

---

vtex/actions/session/createSession.ts
vtex/actions/session/deleteSession.ts
vtex/actions/session/editSession.ts
vtex/loaders/session/getSession.ts
vtex/loaders/session/getUserSessions.ts
vtex/manifest.gen.ts
vtex/utils/openapi/vcs.openapi.gen.ts
vtex/utils/openapi/vcs.openapi.json
vtex/utils/types.ts

This PR adds a bunch of APIs related to session management, such as create, delete, edit and list

Feat(VTEX): Implement Session related APIs

---

pinecone-assistant/actions/delete.ts
pinecone-assistant/actions/search.ts
pinecone-assistant/actions/upload.ts
pinecone-assistant/loaders/get.ts
pinecone-assistant/loaders/list.ts
pinecone-assistant/manifest.gen.ts
pinecone-assistant/mod.ts
pinecone-assistant/utils/client.ts
pinecone-assistant/utils/types.ts

- Introduced new actions for file management: delete and upload.
- Added loaders for retrieving and listing files.
- Updated the search action to include an optional filter parameter.
- Modified the manifest to include new actions and loaders.
- Removed the Content-Type header from API requests for better flexibility.

feat: add file management actions and loaders

---

commerce/types.ts
vtex/utils/transform.ts
vtex/utils/types.ts

It corrects the Profile typing related to an info that exists in the data. And it adds the “neighborhood” value that comes from the vtex API, but isn't passed on in the transform

fix: add addressDistrict and tradeName fields

---

airtable/utils/ui-templates/selection-page.template.html
google-youtube/loaders/videos/captions/get.ts
google-youtube/loaders/videos/captions/getFormated.ts
google-youtube/loaders/videos/captions/list.ts
google-youtube/manifest.gen.ts
google-youtube/utils/client.ts
google-youtube/utils/constant.ts
google-youtube/utils/types.ts

Fix youtube captions

---

pinecone-assistant/actions/search.ts

optionally return snippet.reference.file.metadata on queries

chore(pinecone-assistant): optionally return metadata on file search

---

vtex/mod.ts

Props exist and are used, and were commented on by mistake in this [pr](https://github.com/deco-cx/apps/commit/3bf2b1d60fd1a21ae9c0694db9eb5fc1020b1d96)

fix: reverting vtex app prop that existed and was removed by mistake

---

MAINTAINERS.txt
ai-assistants/mod.ts
commerce/utils/canonical.ts
openai/mod.ts
website/handlers/fresh.ts

- **Summary**: Hardens canonical URL derivation, adds contextual/less noisy abort logging and tracing in Fresh, and makes OpenAI-dependent flows safe when no API key is configured.
- **Key changes**
- **SEO**: `commerce/utils/canonical.ts`
- `canonicalFromBreadcrumblist` now accepts an optional `BreadcrumbList`, gracefully returns `undefined` if missing/empty, and safely selects the highest-position item.
- **Observability/logging**: `website/handlers/fresh.ts`
- `abortHandler` accepts request context (url, path template, UA, referer, startedAt, completion).
- Suppresses noisy abort logs in non-prod and for `/.well-known`, `.css`, `.map`.
- Adds structured logs for first-byte threshold aborts (immediate and delayed) and request aborts.
- Sets tracing attrs: `http.target`, …

Null-safe canonical; richer Fresh abort logs; safe OpenAI init
