commerce/manifest.gen.ts
commerce/types.ts
vtex/loaders/legacy/suggestions.ts
vtex/manifest.gen.ts
vtex/utils/paths.ts
vtex/utils/types.ts
website/manifest.gen.ts

Test it on https://deco-sites-aviator-r3hzqm1as560.deno.dev/

Adding a half-baked support for VTEX Legacy Autocomplete

---

shopify/utils/transform.ts

This PR splits product from sku image so we can easily split these items on the frontend

chore: split product from sku images

---

vtex/loaders/legacy/relatedProductsLoader.ts
vtex/utils/batch.ts

batches fetchs so we don't run into api limits

fix related loader

---

shopify/handlers/sitemap.ts
shopify/loaders/proxy.ts
shopify/manifest.gen.ts

add sitemap handler to shopify app

---

compat/$live/manifest.gen.ts
compat/std/manifest.gen.ts
decohub/manifest.gen.ts
scripts/start.ts
shopify/manifest.gen.ts
vnda/actions/cart/simulation.ts
vnda/hooks/useCart.ts
vnda/manifest.gen.ts
vnda/utils/client/client.ts
vnda/utils/client/types.ts
vnda/utils/openapi/vnda.openapi.gen.ts
vnda/utils/openapi/vnda.openapi.json
vtex/manifest.gen.ts
wake/manifest.gen.ts
website/manifest.gen.ts
workflows/manifest.gen.ts

A função `processTypeInNestedObject` é uma função recursiva que processa um objeto, adicionando "null" ao início do array na propriedade 'type' se a propriedade 'nullable' estiver definida como true.
Antes você não gerava o tipo null em nenhum arquivo.gen. Agora você consegue gerar essa typagem
- `obj` (Object): O objeto a ser processado.
- (Object): O objeto processado.
```javascript
const inputObj = {
type: ["string", "number"],
nullable: true,
innerObj: {
type: "boolean",
nullable: false
}
};
const outputObj = processObj(inputObj);
console.log(outputObj);
```
Foi adicionada no arquivo start.ts para gerar os scripts atualizados. O uso dela foi implementado no body, response e no searchParams.
Antes quando você recebia a propriedade nullable, ficava perdido sem funcionalidade, mas com …

Cep vnda pdp & start.ts FIX

---

vnda/loaders/cart.ts
vnda/utils/openapi/vnda.openapi.gen.ts
vnda/utils/openapi/vnda.openapi.json

Fix the types in vnda.openapi.json.
I change the cart loader types and the return.

Fix-Cart-VNDA

---

algolia/README.md
decohub/README.md
decohub/apps/algolia.ts
decohub/apps/shopify.ts
decohub/apps/typesense.ts
decohub/apps/vnda.ts
decohub/apps/vtex.ts
decohub/apps/wake.ts
decohub/components/Markdown.tsx
decohub/mod.ts
shopify/README.md
typesense/README.md
vnda/README.md
vtex/README.md
wake/README.md

feat: Apps Readme & DecoHub Preview

---

import_map.json
utils/http.ts
vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/intelligentSearch/suggestions.ts
vtex/loaders/legacy/productDetailsPage.ts
vtex/loaders/legacy/productList.ts
vtex/loaders/legacy/productListingPage.ts
vtex/loaders/legacy/relatedProductsLoader.ts
vtex/loaders/legacy/suggestions.ts
vtex/middleware.ts
vtex/mod.ts
vtex/utils/segment.ts
website/handlers/proxy.ts

set-cookie segment once using the new middleware feature

feat middleware

---

vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/intelligentSearch/suggestions.ts
vtex/loaders/legacy/relatedProductsLoader.ts
vtex/utils/legacy.ts
wake/utils/transform.ts
website/loaders/fonts/googleFonts.ts

Uses the global STALE constant instead of redeclaring it every single time

uses the global stale variable

---

algolia/README.md
algolia/actions/index/product.ts
algolia/actions/index/wait.ts
algolia/actions/setup.ts
algolia/loaders/product/list.ts
algolia/loaders/product/listingPage.ts
algolia/loaders/product/suggestions.ts
algolia/manifest.gen.ts
algolia/mod.ts
algolia/utils/product.ts

Creates a button on algolia app preview to setup the indices. From now on, the setup will need to be manually run

Setup algolia once

---

analytics/components/Plausible.tsx
website/components/_Controls.tsx

custom properties on pageviews.

Minor fixes to avoid ios incompability and prepare plausible script to

---

website/sections/Rendering/Deferred.tsx

Allow multiple deferred on the same page

feat: allow multiple deferred same page

---

website/pages/Page.tsx
website/sections/Rendering/Deferred.tsx

Makes the preview work on preview

feat: deferred working now on preview

---

website/loaders/fonts/googleFonts.ts

The loader isn't fetching on google the write font, based on user-agent headers and isn't replacing all urls from stylesheet.
Before: returning .ttf font using chrome, and only 1 because user-agent isn't considered.
After:

fix: googleFonts loader

---

deno.json
website/components/Analytics.tsx

forward preventcollect property to GTM/GA https://github.com/deco-cx/partytown/pull/15

feat: Add preventCollect props analytics

---

vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/intelligentSearch/suggestions.ts
vtex/loaders/legacy/productDetailsPage.ts
vtex/loaders/legacy/productList.ts
vtex/loaders/legacy/productListingPage.ts
vtex/loaders/legacy/relatedProductsLoader.ts
vtex/loaders/legacy/suggestions.ts
vtex/middleware.ts
vtex/utils/segment.ts
vtex/utils/simulation.ts

Somehow, vtex segment was not being kept throughout the navigation. This PR fixes this issues by making the segment cookie to stick

fix: VTEX Segment

---

admin/manifest.gen.ts
algolia/manifest.gen.ts
commerce/manifest.gen.ts
compat/$live/manifest.gen.ts
compat/std/manifest.gen.ts
decohub/manifest.gen.ts
linx/manifest.gen.ts
power-reviews/manifest.gen.ts
shopify/manifest.gen.ts
typesense/manifest.gen.ts
verified-reviews/manifest.gen.ts
vnda/manifest.gen.ts
vtex/manifest.gen.ts
wake/manifest.gen.ts
website/manifest.gen.ts
website/matchers/never.ts
website/matchers/random.ts
workflows/manifest.gen.ts

Add `label` to test and draft matchers

feat: add label to test and draft matchers

---

vnda/loaders/proxy.ts

Thanks Lolja for soliciting this

Adding /pagamento/* to VNDA proxy paths

---

admin/manifest.gen.ts
algolia/manifest.gen.ts
commerce/manifest.gen.ts
compat/$live/manifest.gen.ts
compat/std/manifest.gen.ts
decohub/manifest.gen.ts
linx/manifest.gen.ts
power-reviews/manifest.gen.ts
shopify/manifest.gen.ts
typesense/manifest.gen.ts
verified-reviews/manifest.gen.ts
vnda/manifest.gen.ts
vtex/manifest.gen.ts
wake/manifest.gen.ts
website/manifest.gen.ts
website/matchers/never.ts
website/matchers/random.ts
workflows/manifest.gen.ts

Revert "feat: add label to test and draft matchers"

---

algolia/loaders/product/listingPage.ts
algolia/loaders/product/suggestions.ts
algolia/utils/product.ts

Adds availablity info to index

feat: Algolia availability

---

website/components/_Controls.tsx

On `.` redirects user to admin.deco.cx

feat: use admin-deco-cx

---

compat/std/deps.ts
compat/std/sections/VTEXPortalDataLayerCompatibility.tsx
vtex/components/VTEXPortalDataLayerCompatibility.tsx

Migrate to use new approach of script injection

chore: migrate datalayer compat to apps

---

algolia/sections/Analytics/Algolia.tsx

algolia analytics

---

algolia/loaders/product/listingPage.ts
vtex/actions/cart/addItems.ts
vtex/actions/cart/getInstallment.ts
vtex/actions/cart/removeItemAttachment.ts
vtex/actions/cart/removeItems.ts
vtex/actions/cart/simulation.ts
vtex/actions/cart/updateAttachment.ts
vtex/actions/cart/updateCoupons.ts
vtex/actions/cart/updateItemAttachment.ts
vtex/actions/cart/updateItemPrice.ts
vtex/actions/cart/updateItems.ts
vtex/actions/cart/updateProfile.ts
vtex/actions/cart/updateUser.ts
vtex/loaders/cart.ts
vtex/middleware.ts

Allow setting facets ordering and labels via deco admin

feat: algolia facet labels

---

algolia/utils/product.ts

improve algolia settings

---

commerce/loaders/product/extensions/suggestions.ts
commerce/loaders/product/productListingPage.ts
commerce/loaders/product/products.ts
commerce/manifest.gen.ts
deno.json
vtex/loaders/legacy/suggestions.ts
vtex/loaders/product/extensions/suggestions.ts
vtex/manifest.gen.ts
vtex/utils/extensions/mod.ts
website/loaders/extension.ts

Add suggestions extensions so we can use legacy search suggestions.

feat: suggestions extensions

---

admin/actions/blocks/delete.ts
admin/actions/blocks/newRevision.ts
admin/fsStorage.ts
admin/loaders/blocks/listRevisions.ts
admin/loaders/releases/blocks.ts
admin/manifest.gen.ts
admin/mod.ts
admin/types.ts

- List blocks from storage state
- Delete blocks on storage state

feat: add loaders for fs block storage

---

admin/actions/pages/new.ts
admin/loaders/blocks/latest.ts
admin/loaders/pages/list.ts
admin/manifest.gen.ts
website/components/Image.tsx
website/loaders/image.ts
website/utils/image/engines/passThrough/engine.ts

Create page actions:
- create page
- list pages

feat: add pages actions

---

admin/actions/pages/delete.ts
admin/manifest.gen.ts

Add missing delete page action

feat: add delete page action

---

commerce/sections/Seo/SeoPDP.tsx
commerce/sections/Seo/SeoPLP.tsx
vnda/loaders/productDetailsPage.ts
vnda/loaders/productListingPage.ts
vnda/utils/client/types.ts
vnda/utils/openapi/vnda.openapi.gen.ts
vnda/utils/openapi/vnda.openapi.json
vnda/utils/transform.ts

This PR uses #94 and:
1. fixes canonicals on plp, pdp
2. fixes filters on vnda

fix canonicals

---

admin/loaders/releases/blocks.ts

I am sorry about the commit name

fix: add data level at blocks loader

---

sourei/sections/Analytics/Sourei.tsx

Fixes:
1. Floating point precision in price
2. Index starting

fix: Sourei

---

vtex/hooks/context.ts
vtex/loaders/product/wishlist.ts
vtex/loaders/wishlist.ts

Make product wishlist loader paginated

feat: make wishlist paginated

---

algolia/mod.ts
compat/std/mod.ts
power-reviews/mod.ts
typesense/mod.ts
verified-reviews/mod.ts
vnda/mod.ts
vtex/mod.ts
wake/mod.ts

migrate all apps to use secrets instead of plain string

feat: use secrets

---

wake/mod.ts

Removes throw on tokens missing so we can add it via admin

fix: Remove throw on missing tokens

---

admin/manifest.gen.ts
algolia/manifest.gen.ts
commerce/manifest.gen.ts
compat/$live/manifest.gen.ts
compat/std/manifest.gen.ts
decohub/manifest.gen.ts
linx/manifest.gen.ts
nuvemshop/manifest.gen.ts
power-reviews/manifest.gen.ts
shopify/manifest.gen.ts
verified-reviews/manifest.gen.ts
vnda/manifest.gen.ts
vtex/actions/cart/updateGifts.ts
vtex/hooks/useCart.ts
vtex/manifest.gen.ts
vtex/utils/client.ts
vtex/utils/types.ts
wake/manifest.gen.ts
website/manifest.gen.ts
workflows/manifest.gen.ts

Adicionei uma action no cart para selecionar gifts

[VTEX] feat: Add updateGifts action

---

website/handlers/redirect.ts

Keeping query string on redirects

---

vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/legacy/productDetailsPage.ts

Ignore case on VTEX Product Details Loader

---

platforms/kubernetes/actions/deployments/create.ts
platforms/kubernetes/actions/deployments/rollout.ts
platforms/kubernetes/actions/domains/create.ts
platforms/kubernetes/platform.ts

Previously it was pointing to the latest version instead of production version

Fixes domain mapping route

---

website/handlers/router.ts

change the priority of : and *

---

vtex/loaders/legacy/brands.ts
vtex/manifest.gen.ts
vtex/utils/client.ts
vtex/utils/transform.ts
vtex/utils/types.ts

This PR adds the brand list loader, which returns brands registered in VTEX

[VTEX] - Add brand list loader

---

vtex/utils/legacy.ts

It should be default, who wants different, needs to customize.

fix canonical to lowercase

---

admin/manifest.gen.ts
algolia/manifest.gen.ts
commerce/manifest.gen.ts
compat/$live/manifest.gen.ts
compat/std/manifest.gen.ts
decohub/manifest.gen.ts
linx/manifest.gen.ts
nuvemshop/manifest.gen.ts
platforms/kubernetes/manifest.gen.ts
power-reviews/manifest.gen.ts
shopify/manifest.gen.ts
verified-reviews/loaders/productList.ts
verified-reviews/loaders/productListingPage.ts
verified-reviews/manifest.gen.ts
verified-reviews/utils/client.ts
verified-reviews/utils/transform.ts
vnda/manifest.gen.ts
vtex/manifest.gen.ts
vtex/utils/legacy.ts
wake/manifest.gen.ts
website/manifest.gen.ts
workflows/manifest.gen.ts

FEAT/PLP Extension  (Verified reviews)

---

decohub/manifest.gen.ts
vtex/loaders/collections/list.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/legacy/productList.ts
vtex/manifest.gen.ts
vtex/utils/types.ts

add dynamic collections to props at product list loader

---

vtex/loaders/legacy/productListingPage.ts

[ VTEX ] FIX Canonical in PLP

---

vnda/utils/transform.ts

In this fix I repair the urls generations in deco. 
In this first image we have the issue:
In this second image we have the right way:

FIX/PLP - Filters urls

---

vtex/utils/transform.ts

Revert "feat: Ignore case when check for selected filter"

---

website/loaders/options/routes.ts
website/loaders/routes.ts
website/manifest.gen.ts

This PR adds a new loader to use as dynamic options, this loader returns all pages created in deco and uses their route as a value, useful when you need to choose a route in some apps configuration

[Website] - Add "routes" dynamic loader

---

verified-reviews/utils/client.ts

[Verifed Reviews] - PDP

---

linx/mod.ts

Reverts deco-cx/apps#419
Adds a explicit comment to the linx app.

enable linx cache

---

website/components/_Controls.tsx

LiveControls: open cms in new tab

---

analytics/loaders/DecoAnalyticsScript.ts
website/components/_Controls.tsx
website/handlers/router.ts

Add hash at manual plausible script

---

vnda/loaders/productListingPage.ts

In this pr I add PriceRange. Now you can decide min and max price for you PLP like vtex.
"/categoria/de-min-a-max" | "/termo/de-min-a-max" | "/s/de-min-a-max?q=xpto"
https://www.velocita.com.br/tenis-de-corrida/de-1200-a-1500
https://www.velocita.com.br/s/de-1200-a-1500?q=

[ Vnda ] - PriceRange

---

wap/loaders/productListingPage.ts
wap/loaders/proxy.ts
wap/utils/openapi/api.openapi.gen.ts
wap/utils/openapi/api.openapi.json

Fix Wap proxy.
add Order and Filter as CMS props
(https://www.loom.com/share/d3a1f1590408489da4deef29e5679958)

Wap Proxy and PLP filters and sort

---

commerce/manifest.gen.ts
commerce/mod.ts
commerce/sections/Seo/SeoPDP.tsx
commerce/sections/Seo/SeoPDPV2.tsx
commerce/sections/Seo/SeoPLP.tsx
commerce/sections/Seo/SeoPLPV2.tsx
compat/std/sections/SEOPDP.tsx
compat/std/sections/SEOPLP.tsx
website/Preview.tsx
website/components/Seo.tsx
website/manifest.gen.ts
website/mod.ts
website/pages/Page.tsx
website/sections/Seo/Seo.tsx
website/sections/Seo/SeoV2.tsx

This depends on https://github.com/deco-cx/deco/pull/596

feat(website/commerce): Add seo property for pages and PDP/PLP section preview

---

vnda/handlers/sitemap.ts
vnda/loaders/proxy.ts
vnda/manifest.gen.ts
website/handlers/proxy.ts

SiteMap
https://velocita.deco.site/sitemap.xml

Sitemap vnda

---

vnda/loaders/productListingPage.ts
vnda/mod.ts

In this pr we fix how we verify if is a searchPage or no.

[FIX] searchPages in vnda

---

vnda/utils/transform.ts

Removing pagination in filter urls in VNDA

---

vnda/loaders/productListingPage.ts
vnda/mod.ts
vnda/utils/transform.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/legacy/productList.ts
vtex/utils/transform.ts

https://github.com/deco-cx/apps/assets/76620866/22fb4c3f-d7b9-46cb-bfb9-568fab87a17b

add sort to product list when input is id or sku

---

website/loaders/redirectsFromCsv.ts

If there are for example 5 redirectsFromCsv, only the first was called. This pr makes everyone called correctly

fix: Only first redirectFromCsv works

---

.github/workflows/update.yml

ci: add updater

---

nuvemshop/loaders/proxy.ts
shopify/loaders/proxy.ts
vnda/loaders/proxy.ts
vtex/loaders/proxy.ts
wake/loaders/proxy.ts
website/handlers/sitemap.ts

add possibility to exclude paths from deco_sitemap

---

platforms/kubernetes/common/cmds/build.ts

https://github.com/denoland/fresh/pull/2035

define min versions for fresh and preact to use precompile

---

platforms/kubernetes/common/cmds/build.ts

Revert "Remove precompile"

---

platforms/kubernetes/common/cmds/build.ts

Remove preact precompile override

---

platforms/kubernetes/common/knative/deployments.ts

adjust default values for resources on k8s

---

platforms/kubernetes/actions/build.ts
platforms/kubernetes/common/cmds/build.ts
platforms/kubernetes/common/jobs.ts
platforms/kubernetes/common/knative/deployments.ts
platforms/kubernetes/common/knative/route.ts
platforms/kubernetes/common/watcher.ts

- Wait route to be ready (meaning that the check will only be green if route is available)
- Reuse start cache when site cache is not available (first build)

Wait route to be ready

---

platforms/kubernetes/actions/deployments/create.ts
platforms/kubernetes/actions/deployments/rollout.ts
platforms/kubernetes/actions/sites/create.ts
platforms/kubernetes/common/knative/deployments.ts
platforms/kubernetes/mod.ts
platforms/kubernetes/platform.ts

Production with default state
Production with customized state
Preview (always forced state)

prune preview and deprecate props

---

platforms/kubernetes/actions/deployments/create.ts
platforms/kubernetes/actions/sites/create.ts
platforms/kubernetes/common/knative/deployments.ts
platforms/kubernetes/mod.ts
platforms/kubernetes/platform.ts
website/loaders/fonts/googleFonts.ts

Adjust production state when updating

---

linx/loaders/auction/ListBids.ts
linx/loaders/auction/detailsPage.ts
linx/manifest.gen.ts
linx/mod.ts
linx/utils/client.ts
linx/utils/types/ListBidsJSON.ts

Ajustes Auctions

---

blog/utils/records.ts

fix: blog post loaders

---

website/mod.ts

Fix theme selector by adding default theme property

fix: default theme selector

---

website/components/_Controls.tsx

change pathname to a generic path at admin

---

blog/mod.ts
blog/sections/Seo/SeoBlogPost.tsx

feat(blog): adds website app as dependecy

---

utils/fetch.ts

remove memory leak??

---

blog/mod.ts
blog/sections/Seo/SeoBlogPost.tsx

Revert "feat(blog): adds website app as dependecy"

---

platforms/kubernetes/actions/sites/create.ts
platforms/kubernetes/common/knative/deployments.ts
platforms/kubernetes/common/knative/service.ts
platforms/kubernetes/loaders/siteState/get.ts
platforms/kubernetes/platform.ts

adds labeled nodes concept during pod deployments and sites creation

---

deno.json

bump versions

---

website/loaders/redirects.ts

change includes to check slug after slash

---

ai-assistants/mod.ts
decohub/components/Markdown.tsx

Do not fail on fetch markdown

---

deno.json

bump std version

---

website/handlers/proxy.ts
website/mod.ts

add native ab testing at website

---

shopify/loaders/proxy.ts
website/handlers/proxy.ts

improve shopify proxy pages

---

website/mod.ts

fix description

---

vtex/actions/cart/clearOrderformMessages.ts
vtex/hooks/useCart.ts
vtex/manifest.gen.ts
vtex/utils/client.ts

This contribuition adds the `clearOrderformMessages` action to clear messages field of orderform, this is usefull when you use the messages to show to final user.

feat: create clear orderform messages

---

platforms/kubernetes/actions/sites/create.ts
platforms/kubernetes/loaders/siteState/get.ts
platforms/kubernetes/platform.ts

remove node selector and affinities

---

website/pages/Page.tsx

add noindex tag to specific domains

---

decohub/mod.ts
vnda/loaders/productListingPage.ts
vnda/utils/transform.ts

fix import external apps

---

platforms/kubernetes/common/cmds/run.ts

Allow override deno.lock

---

website/matchers/location.ts

fix location header exclude location

---

website/loaders/asset.ts

fix(website): asset loader issue

---

vnda/actions/notifyme.ts
vnda/manifest.gen.ts

It's about a notifyme action.
https://deco-sites-velocita-js2j8gn9cycx.deno.dev/produto/tenis-asics-metaspeed-sky-paris-unissex-15294?skuId=1013A123-600-36

[ Vnda ] warn-me

---

platforms/kubernetes/actions/deployments/rollout.ts
platforms/kubernetes/common/knative/revisions.ts
platforms/kubernetes/common/objects.ts
website/mod.ts

change matcher hard to matcher from panel

---

platforms/kubernetes/common/knative/revisions.ts
platforms/kubernetes/constants.ts

Updating min-scale to zero in Autoscaler

---

analytics/loaders/DecoAnalyticsScript.ts
platforms/kubernetes/common/knative/revisions.ts

migrate get flags to client-side

---

platforms/kubernetes/common/cmds/cmd.ts
platforms/kubernetes/common/cmds/hypervisor.ts

Add hypervisor persistence

---

deno.json
magento/hooks/context.ts
magento/hooks/useCart.ts
magento/runtime.ts

Magento useCart()

---

linx/loaders/auction/list.ts

Update facets auction - list.ts

---

htmx/mod.ts
htmx/sections/htmx.tsx

Move config to htmx app definition

fix: htmx config

---

admin/github/handler.ts
admin/github/prClose.ts
admin/mod.ts
admin/platform.ts
admin/play/platform.ts
platforms/kubernetes/actions/deployments/create.ts
platforms/kubernetes/actions/routes/delete.ts
platforms/kubernetes/common/knative/deployments.ts
platforms/kubernetes/manifest.gen.ts
platforms/kubernetes/platform.ts
platforms/subhosting/platform.ts

Create deployment branch only + delete on close PR

---

magento/actions/cart/removeItem.ts
magento/hooks/useCart.ts
magento/manifest.gen.ts
magento/utils/client/client.ts

feat: adding remove item from cart

---

magento/utils/stringifySearchCriteria.ts

refactor: SearchCriteria interface refactoring

---

shopify/loaders/ProductList.ts
shopify/loaders/ProductListingPage.ts
shopify/loaders/RelatedProducts.ts

For async rendering work well, we actually need the loaders to throw

fix: shopify loaders for async rendering

---

vtex/hooks/useCart.ts

Enqueue all cart actions

---

magento/loaders/user.ts
magento/manifest.gen.ts
magento/utils/client/client.ts
magento/utils/client/types.ts
magento/utils/user.ts

It's about an user loader.
You need to pass this cookie to test:
```js
PHPSESSID=248288ceab59a59ba6d3c03e65193df9;'
```
Or do this curl request to see the data: 
```js
curl 'https://www.granado.com.br/granado/customer/section/load?sections=customer,carbono-customer' \
-H 'cookie: PHPSESSID=248288ceab59a59ba6d3c03e65193df9;'
```

[ Magento ] - users

---

deno.json
htmx/manifest.gen.ts
htmx/mod.ts
htmx/sections/Deferred.tsx
website/handlers/fresh.ts
website/mod.ts

Add htmx deferred section

---

algolia/loaders/client.ts
algolia/manifest.gen.ts
algolia/mod.ts
algolia/utils/product.ts

Now you can invoke this client or just use it with props.

[ Algolia ] Client Headless

---

linx/loaders/product/listingPage.ts

Update listingPage.ts with totalPages

---

magento/loaders/productDetailsPage.ts
magento/mod.ts
magento/utils/client/types.ts
magento/utils/transform.ts

fix(magento): installments

---

linx/utils/transform.ts

Ajuste estoque produto

---

compat/std/sections/Analytics.tsx
vtex/components/VTEXPortalDataLayerCompatibility.tsx
website/components/Analytics.tsx

After this PR, you will be able do remove `partytown/` entries from your deno.json.
We still need to keep the partytown on this one because of the std compatiblity layer

chore: Remove partytown mentions

---

deno.json

Release [0.45.0]

---

deno.json

Release [0.45.1]

---

magento/actions/newsletter/subscribe.ts
magento/manifest.gen.ts
magento/utils/client/client.ts
magento/utils/client/types.ts

feat(magento): subscribe newsletter

---

magento/actions/cart/addCoupon.ts
magento/actions/cart/removeCoupon.ts
magento/hooks/useCart.ts
magento/manifest.gen.ts
magento/utils/client/client.ts
magento/utils/clientGraphql/types.ts

feat: add action, add and remove coupon

---

magento/loaders/productDetailsPage.ts

feat: add cache

---

sourei/sections/Analytics/Sourei.tsx
utils/defaultErrorPage.tsx
website/components/_Controls.tsx
website/components/_seo/Slack.tsx
website/sections/Rendering/Deferred.tsx
website/sections/Seo/SeoV2.tsx

Use generic templates on SEO if not defined

---

deno.json

Release [0.45.2]

---

magento/loaders/product/detailsPage.ts
magento/loaders/product/getId.ts
magento/loaders/product/list.ts
magento/loaders/product/listingPage.ts
magento/mod.ts

feat(magento): optional cache

---

magento/actions/cart/addCoupon.ts
magento/utils/cart.ts

Magento bugfix/add coupon

---

vtex/utils/transform.ts

change object from we get specifications

---

magento/loaders/cart.ts
magento/utils/cart.ts

feat(magento) - cart fallback

---

linx/utils/transform.ts

Adicionar código de identificação SKU

Adicionar código de identificação SKU

---

magento/actions/cart/addCoupon.ts
magento/actions/cart/addItem.ts
magento/actions/cart/removeCoupon.ts
magento/actions/cart/removeItem.ts
magento/actions/cart/setSimulation.ts
magento/actions/cart/updateItem.ts
magento/utils/cart.ts

feat(magento): cart fallback

---

shopify/utils/cart.ts

add decode URI to getCartCookie shopify

---

linx/utils/transform.ts

add color in product options to product additional property

add color in product options to product additional property

---

compat/std/sections/Analytics.tsx
website/components/Analytics.tsx

fix: analytics magento

---

compat/std/sections/Analytics.tsx
website/components/Analytics.tsx

fix: analytics noscript src

---

magento/loaders/proxy.ts
magento/manifest.gen.ts

fix(magento): proxies logic

---

magento/loaders/proxy.ts

Magento fix redirects

---

magento/actions/cart/addItem.ts
magento/middleware.ts

Cookie priority high

---

magento/loaders/product/listingPage.ts
magento/utils/clientGraphql/queries.ts
magento/utils/utils.ts

fix: changing the search from url_path to url_key

---

magento/loaders/cart.ts
magento/utils/cart.ts

fix: using parallelization and decreasing loops

---

magento/loaders/cart.ts
magento/loaders/product/images.ts
magento/manifest.gen.ts
magento/utils/cart.ts
magento/utils/clientGraphql/queries.ts
magento/utils/clientGraphql/types.ts

Magento poc graphql cart images

---

magento/actions/cart/setSimulation.ts

Await simulation

---

magento/loaders/product/detailsPageGQL.ts
magento/loaders/product/listingPage.ts
magento/utils/clientGraphql/queries.ts
magento/utils/clientGraphql/types.ts
magento/utils/transform.ts

fix(magento): plp url

---

magento/loaders/product/listingPage.ts
magento/utils/clientGraphql/queries.ts
magento/utils/clientGraphql/types.ts
magento/utils/transform.ts
magento/utils/utils.ts

fix(magento): urlkey

---

anthropic/actions/code.ts
anthropic/actions/stream.ts
anthropic/mod.ts

add support to anthropic sonnet 3.5 model

feat: add support to anthropic sonnet 3.5 model

---

htmx/sections/Deferred.tsx
utils/deferred.ts
website/handlers/fresh.ts
website/sections/Rendering/Deferred.tsx

chore: render deferred if it's bot or __decoFBT=0

---

magento/README.md
magento/mod.ts

feat(magento): doc started

---

magento/loaders/cart.ts
magento/loaders/extensions/cart/cart.ts
magento/manifest.gen.ts
magento/mod.ts
magento/utils/client/client.ts
magento/utils/client/types.ts
magento/utils/extensionsUtils.ts

feat(magento): cart extension

---

admin/widgets.ts

This Pull Request adds new types to the `widgets.ts` file, enhancing the usability of Deco Widgets for developers. With these changes, users can directly import the types into their code, simplifying widget development and maintenance.
- **Addition of new types with specific formatting:**
- `TextArea`: Represents a text area.
- `RichText`: Represents formatted text.
- `ColorInput`: Represents a color input, with a default value of `#000000`.
- `CSSCode`: Represents CSS code.
- `TypescriptCode`: Represents TypeScript code.
- `JSONCode`: Represents JSON code.
- **Along with the existing types:**
- `ImageWidget`: Represents an image URI.
- `HTMLWidget`: Represents an HTML string.
- `VideoWidget`: Represents a video URI.
- `SiteRoute`: Represents a dynamic route with options loaded from …

feat: new types added to widgets

---

magento/loaders/cart.ts
magento/utils/cache.ts
magento/utils/cart.ts

fix(magento): images on cart

---

htmx/mod.ts
vtex/utils/transform.ts
vtex/utils/types.ts
wake/actions/cart/updateItemQuantity.ts

Wrong path: https://cdn.jsdelivr.net/npm/htmx.org@1.9.11/dist/ext/web-sockets.js
Correct path: https://cdn.jsdelivr.net/npm/htmx.org@1.9.11/dist/ext/ws.js

Fix websocket HTMX extension name

---

records/utils.ts

Fix the Invalid_url error running the SQLite on windows localhost.

fix: records to run with local db on windows

---

anthropic/actions/stream.ts

Adding enableTools - Decopilot's function call

---

website/components/Image.tsx

Offload image traffic to ecommerce platform. 
This PR works only behind a new flag. We'll eventually enable this flag on some accounts to test a hypothesis

redirect image traffic

---

website/components/Events.tsx
website/components/Image.tsx

This PR makes the Image component carry the env var into the frontend

fix: add feature flag on the frontend for image component

---

commerce/sections/Seo/SeoPDPV2.tsx
commerce/sections/Seo/SeoPLPV2.tsx
decohub/mod.ts
deno.json
htmx/sections/Deferred.tsx
utils/deferred.tsx
website/components/_Controls.tsx
website/manifest.gen.ts
website/sections/Rendering/Deferred.tsx
website/sections/Rendering/SingleDeferred.tsx

this contributes on this new `async render default` https://github.com/deco-cx/community/issues/13

feat(website): section SingleDeferred

---

records/deps.ts
records/mod.ts

feat: use dynamic import for libsql run locally

---

vtex/loaders/legacy/productDetailsPage.ts
vtex/utils/legacy.ts

Ir product is missing title, use its name as fallback.

Use name as title SEO fallback

---

vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/legacy/productListingPage.ts

find first item available befor get 0

---

blog/loaders/BlogPostPage.ts
blog/types.ts

Add SEO properties to posts so they are displayed on the blog interface.

feat: add seo to blog post props

---

deno.json
vtex/loaders/options/productIdByTerm.ts
vtex/manifest.gen.ts
vtex/utils/types.ts

add dynamic options

---

vtex/loaders/masterdata/searchDocuments.ts
vtex/manifest.gen.ts
vtex/utils/openapi/vcs.openapi.gen.ts
vtex/utils/openapi/vcs.openapi.json
vtex/utils/types.ts

This PR adds a loader that searches documents in masterdata by its acronym.

feat(VTEX): add "Search Document" masterdata loader

---

deno.json
shopify/loaders/ProductList.ts
utils/cookie.ts
website/components/Events.tsx
website/handlers/router.ts
website/pages/Page.tsx

Import from deco/mod.ts instead of internal files

---

vtex/loaders/config.ts

This adds the myvtex context to config.ts, so you can use it in actions of reviews and ratings

configuring myVtex app context to use in reviews and ratings POST req

---

website/components/Clickhouse.tsx
website/pages/Page.tsx

Add user id on clickhouse without setting cookies

---

vtex/loaders/legacy/productList.ts

fix: add cache key for sku/product ids at vtex/legacy/productList

---

vtex/loaders/masterdata/searchDocuments.ts
vtex/utils/ajustLimits.ts
vtex/utils/resourceRange.ts

Ajusting the range of searchDocuments

Fix search documents vtex

---

blog/loaders/BlogpostList.ts
blog/loaders/BlogpostListing.ts
blog/manifest.gen.ts
blog/sections/Seo/SeoBlogPostListing.tsx
blog/types.ts
blog/utils/constants.ts
blog/utils/handlePosts.ts
website/functions/requestToParam.ts

Added some new features to blog - now, is possible to filter and order the posts

Feat blog listing page

---

vtex/loaders/intelligentSearch/productDetailsPage.ts
vtex/loaders/intelligentSearch/productList.ts
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/legacy/productDetailsPage.ts
vtex/loaders/legacy/productList.ts
vtex/loaders/legacy/productListingPage.ts
vtex/loaders/legacy/relatedProductsLoader.ts
vtex/utils/intelligentSearch.ts
vtex/utils/legacy.ts
vtex/utils/segment.ts

related to: https://github.com/deco-cx/apps/issues/774.
This PR improve the vtex/loaders to ignore unused querystring on cacheKey

feat (vtex): loaders cache key to prevent vary on any querystring

---

vtex/loaders/legacy/productListingPage.ts

fix(vtex): legacy plp loader cacheKey

---

vtex/loaders/orders/list.ts
vtex/manifest.gen.ts
vtex/utils/client.ts
vtex/utils/openapi/vcs.openapi.gen.ts
vtex/utils/openapi/vcs.openapi.json
vtex/utils/types.ts

We needed that loader in this PR: https://github.com/deco-sites/farmrio/pull/32 to retrieve the orders list.
WIP
https://github.com/deco-sites/farmrio/pull/32

VTEX Loader | Get Orders List

---

website/mod.ts
website/pages/Page.tsx

check if theme exists to add on global sections

---

compat/$live/pages/LivePage.tsx

Fix: LivePage exports

---

deno.json

Release [0.56.11]

---

linx/utils/transform.ts

Add prop type association to associationProperties in to transform.ts

---

.github/issue_template.md
CODE-OF-CONDUCT.md
CONTRIBUTING.md
commerce/types.ts

add null as possibility to avoid crash

---

website/handlers/router.ts

only add search if we have search

---

decohub/apps/posthog.ts
decohub/manifest.gen.ts
posthog/mod.ts
website/handlers/router.ts

Add posthog to decohub.
- Issue: https://github.com/deco-cx/apps/issues/847

Add posthog to decohub

---

website/pages/Page.tsx

Fix resovle chain on globals, so it can be rendered with a partials unique ID.
- Issue: https://github.com/deco-cx/apps/issues/854

Fix resolver chain on Page global sections

---

vtex/utils/transform.ts

This adds the ability to identify offers with default sellers, useful with a "marketplace" system where products can be sold by other sellers

feat(vtex): add sellerDefault to offers

---

deno.json
files/loaders/app.ts
mailchimp/actions/subscribe.ts
resend/README.md
sap/mod.ts
sap/runtime.ts
website/loaders/pages.ts
website/loaders/redirects.ts

fix deco imports

---

blog/actions/submitComment.ts
blog/db/schema.ts
blog/loaders/extensions/BlogpostList/comments.ts
blog/loaders/extensions/BlogpostListing/comments.ts
blog/loaders/extensions/BlogpostPage/comments.ts
blog/manifest.gen.ts
blog/types.ts
blog/utils/records.ts

Feat blog comment

---

admin/widgets.ts

add csv and pdf widgets

---

posthog/components/PostHog.tsx
shopify/loaders/ProductListingPage.ts
vtex/loaders/product/extend.ts

Posthog event is `$pageview`. Current code uses `pageview` as the event name.

Fix posthog pageview event

---

shopify/loaders/ProductListingPage.ts

This PR add "recordPerPage" to the `ProductListingPage` loader return.

[Shopify] Add Record per page

---

vtex/loaders/options/productIdByTerm.ts

improve return of product on dynamic options

---

commerce/types.ts
vtex/actions/profile/newsletterProfile.ts
vtex/actions/profile/updateProfile.ts
vtex/loaders/user.ts
vtex/manifest.gen.ts

Adding the possibility to obtain and edit user data and to subscribe or unsubscribe from the newsletter in my account

feat: my account vtex profile

---

vtex/loaders/proxy.ts
website/handlers/proxy.ts
website/mod.ts

feat: add include script to body in proxies

---

shopify/loaders/proxy.ts
vtex/actions/wishlist/addItem.ts

- Issue: #919 
Try to add an item in this page to your wishlist;
https://www.bagaggio.com.br/carteiras/carteira-masculina?sort=release%3Adesc&page=1

fix(vtex): wishlist loader

---

shopify/loaders/ProductListingPage.ts
shopify/utils/storefront/queries.ts
shopify/utils/transform.ts

Add seo to plp loader (title, description and canonical)

[Shopify] Add Seo loader PLP

---

shopify/loaders/ProductListingPage.ts
shopify/utils/transform.ts
vtex/utils/client.ts
vtex/utils/openapi/vcs.openapi.gen.ts
vtex/utils/openapi/vcs.openapi.json

Fix lint and check 0 62 7

---

vtex/loaders/intelligentSearch/productListingPage.ts
vtex/mod.ts

Improve public url vtex description

---

website/components/Image.tsx

adds myvtex.com in vtex regex.
- Issue: #930 

feat: adds myvtex.com to vtex image url pattern

---

website/handlers/proxy.ts

Atualmente estamos com um bug no proxy do Sitemap.xml. O fato de haver um ? mockado está causando um retorno de 404, quando é adicionado direto no objeto URL funciona. Não deve causar breaking change.

[FIX] - search on proxy

---

vtex/loaders/options/productIdByTerm.ts
website/components/Image.tsx
website/handlers/proxy.ts

improve dynamic-options id loader

---

vtex/loaders/product/extend.ts

filter products before extends

---

vtex/actions/masterdata/updatePartialDocument.ts

(feat): creating an action for vtex masterdata's updatePartialDocument

---

README.md

faster way to generate a release

---

website/matchers/random.ts

We understand that is importante change the cookie name when users change the traffic changes.

add sessionKey func

---

deno.json
vtex/loaders/intelligentSearch/productListingPage.ts
vtex/loaders/legacy/productListingPage.ts
vtex/utils/legacy.ts
vtex/utils/openapi/vcs.openapi.gen.ts

feat: Put the name of the collection in the page title

---

commerce/types.ts
vtex/utils/openapi/vcs.openapi.gen.ts
vtex/utils/transform.ts
vtex/utils/types.ts
wake/loaders/productDetailsPage.ts
wake/loaders/productListingPage.ts

feat: add pickupHolidays type

---

website/components/OneDollarStats.tsx

remove duplicated pageview

---

website/components/OneDollarStats.tsx

It is current sending two pageview events, but Onedollar team is working on that.

add pageview to onedollar

---

shopify/utils/transform.ts
utils/normalize.ts
vtex/utils/segment.ts

Remove Slash from UTM

---

utils/normalize.ts
vtex/utils/segment.ts

cleanup dot in utm_sources

---

blog/manifest.gen.ts
decohub/apps/google-sheets.ts
decohub/manifest.gen.ts

remove gsheets from decohub

---

linx/loaders/product/list.ts
linx/loaders/product/listingPage.ts

Fix linx leak on promise all

---

linx/utils/transform.ts

Avoid GMT-3 on timezone from api auctions list

---

.github/workflows/ci.yaml
analytics/components/DecoAnalytics.tsx
linx/manifest.gen.ts
shopify/loaders/shop.ts
shopify/utils/transform.ts
vtex/utils/openapi/vcs.openapi.json

Avoid window usage plausible

---

streamshop/sections/Carousel.tsx
streamshop/sections/Info&Reels.tsx
streamshop/sections/Stories.tsx

What is this Contribution About?
This commit includes various adjustments requested by the client and the Stream Shop owners, focusing on improving the user experience and addressing key feedback points.

fix: ajustes on info&reels

---

streamshop/sections/Carousel.tsx
streamshop/sections/Stories.tsx

New Streamshop SDK and update imports

fix: update streamshop sdk

---

vtex/loaders/intelligentSearch/productList.ts

query is not required

---

commerce/sections/Seo/SeoPDPV2.tsx
commerce/sections/Seo/SeoPLPV2.tsx
vtex/loaders/intelligentSearch/productList.ts
website/loaders/secret.ts

Revert "Refactor(SEO): show structured data only to bots/crawlers"

---

vtex/loaders/intelligentSearch/productList.ts
website/loaders/secret.ts

Fix type on product list from VTEX IS

---

vtex/loaders/logistics/listPickupPoints.ts
vtex/loaders/logistics/listPickupPointsByLocation.ts
vtex/utils/transform.ts

Feat(VTEX): Add 'isActive' to additionalProperty from 'Place' object

---

commerce/sections/Seo/SeoPDPV2.tsx
commerce/sections/Seo/SeoPLPV2.tsx

Feat(SEO): Ability to prevent structured data to be sent to real users

---

website/pages/Page.tsx

verify pages before iterate

---

linx-impulse/sections/Analytics/LinxImpulsePageView.tsx

This PR create the pageview event of Linx Impulse on the server side to prevent send all page data to front.
We can get up to 2MB of bandwidth reduce
before: 
after: 
https://www.loom.com/share/96981396e0094a3dbada5a7d65101442?sid=f8e46ce5-e274-465c-8a7f-1cd3969c59c3

[Linx-Impulse] create pageview event on server to reduce the bandwidth

---

deco.ts
tiptap-cloud/manifest.gen.ts

fix tiptap bundle

---

tiptap-cloud/actions/createDocument.ts
tiptap-cloud/actions/updateDocument.ts

Fix: create

---

vnda/loaders/productDetailsPage.ts

[VNDA] feat: add pdp cache key for vnda

---

vnda/loaders/productList.ts

Add cache for PL loader on VNDA integration

[VNDA] feat: add cache on PL loader on vnda

---

vnda/loaders/productListingPage.ts

[Feat] - add cache key in PLP at vnda

---

grain/mod.ts
resend/mod.ts
slack/mod.ts

Adding app logos

---

grain/mod.ts
resend/mod.ts
slack/mod.ts
tiptap-cloud/mod.ts
vertex/mod.ts
vtex/mod.ts

https://github.com/deco-cx/apps/pull/1077

continue: Add app logos

---

stability/mod.ts

Update Stability logo URL for improved branding consistency

---

tiptap-cloud/actions/createDocument.ts
tiptap-cloud/actions/updateDocument.ts
tiptap-cloud/utils.ts

Update content now uses string instead of json

---

figma/manifest.gen.ts

Rebuild manifest.gen.ts for figma.

Fix figma manifest

---

figma/mod.ts
stability/manifest.gen.ts

chore: change figma logo

---

vidu/actions/imageToVideo.ts
vidu/actions/referenceToVideo.ts
vidu/actions/startEndToVideo.ts
vidu/actions/textToVideo.ts
vidu/loaders/resultPreview.ts
vidu/mod.ts

Vidu installation

---

website/handlers/router.ts

This reverts commit ce2759148fff7b31017b1909d825c256fee3e7a8.

Revert "fix: url pattern build to handle optional paths (#1094)"

---

openai-mcp/actions/editImage.ts
openai-mcp/actions/generateImage.ts

- Updated `editImageAction` and `generateImageAction` to log errors to the context in addition to the console.
- Modified error messages written to presigned URLs to include the specific error details for better debugging.

Enhance error handling in image processing actions

---

deno-deploy/README.md
deno.json
workflows/deps.ts

[Fix] - replace denopkg to jsdelivr.net

---

elevenlabs/actions/getSharedVoices.ts
elevenlabs/audio-model.ts
elevenlabs/manifest.gen.ts
elevenlabs/types/audio-provider.ts
elevenlabs/types/audio.ts

Adding shared voices endpoint

---

openai-mcp/actions/editImage.ts
openai-mcp/actions/generateImage.ts

- Changed `presignedUrl` from optional to required in the `editImage` interface.
- Removed deprecated model and format parameters from both `editImage` and `generateImage` actions.
- Updated handling of image quality and background options for better clarity and consistency.
- Streamlined the process of generating and editing images, ensuring better error handling and response structure.
- Improved documentation for parameters and their usage across both actions.
> Record a quick screencast describing your changes to help the team understand and review your contribution. This …

Refactor image editing and generation actions

---

vtex/loaders/proxy.ts
website/handlers/sitemap.ts

Feat: Manually insert paths into deco sitemap

---

website/loaders/asset.ts
website/loaders/image.ts

Avoid whitelist on empty array

---

website/handlers/sitemap.ts

It was broken when using URLs with "&"

improve sanitize sitemap function

---

README.md
sienge/actions/cotacoes-de-precos/adicionarFornecedorItem.ts
sienge/actions/cotacoes-de-precos/atualizarItemNegociacao.ts
sienge/actions/cotacoes-de-precos/atualizarNegociacao.ts
sienge/actions/cotacoes-de-precos/autorizarUltimaNegociacao.ts
sienge/actions/cotacoes-de-precos/criarCotacao.ts
sienge/actions/cotacoes-de-precos/criarItemCotacao.ts
sienge/actions/cotacoes-de-precos/criarItemCotacaoDeSolicitacao.ts
sienge/actions/cotacoes-de-precos/criarNegociacaoFornecedor.ts
sienge/clients/purchaseQuotations.ts
sienge/loaders/cotacoes-de-precos/buscarCotacoesComNegociacoes.ts
sienge/manifest.gen.ts
utils/http.ts
website/manifest.gen.ts

More Sienge loaders and debug HTTP mode fix

---

browser-use/client.ts

Use type string literal instead of enums

fix browser-use

---

google-sheets/actions/batchUpdateValues.ts
google-sheets/actions/updateValues.ts
google-sheets/loaders/getSpreadsheet.ts
google-sheets/mod.ts
google-sheets/utils/constant.ts
google-sheets/utils/mappers.ts
google-sheets/utils/types.ts

Updating the Google Sheets MCP so that getSpreadsheet.ts returns more useful data for LLM
funcionando so olhando o metadado, isso vai ser util tanto para o seu caso quanto para deixar o MCP melhor e mais fluido dando o contexto necessário para a LLM
```json
"structuredContent": {
"spreadsheetId": "idExample",
"title": "Planilha de Teste",
"url": "linkExample",
"locale": "pt_BR",
"sheets": [
{
"id": 0,
"title": "Página1",
"rowCount": 1000,
"columnCount": 26,
"dataRange": "Página1!A1:D13",
"filledCells": 52
}
]
},
```
##invented data for testing

Update google sheets

---

airtable/actions/createField.ts
airtable/actions/updateField.ts

Fix redirect uri airtable

---

google-gmail/actions/sendEmail.ts

Fixed special char in gmail title

fix(apps): fixed title

---

slack/client.ts
slack/loaders/channels.ts

chore: add filter types to slack

---

google-sheets/actions/addFormula.ts
google-sheets/actions/copySheet.ts
google-sheets/actions/createSheet.ts
google-sheets/actions/deleteSheet.ts
google-sheets/loaders/getEmptyColumn.ts
google-sheets/loaders/getSheetHeaders.ts
google-sheets/loaders/query.ts
google-sheets/manifest.gen.ts
google-sheets/utils/queryBulder.ts

Mcp sheets query

---

google-sheets/loaders/query.ts
google-sheets/utils/constant.ts

refactor: add constant for row numbering formula in Google Sheets

---

vtex/actions/payment/deletePaymentToken.ts
vtex/loaders/payment/paymentSystems.ts
vtex/loaders/payment/userPayments.ts
vtex/manifest.gen.ts

This PR adds 3 APIs from VTEX related to payments
1. Delete payment token, used to delete users saved credit card.
2. Payment Systems, retrieves payment systems that are setup on vtex.
3. User Payments, retrieves all users saved credit cards.

Feat(VTEX): Implement Payment related APIs

---

superfrete/actions/cancel-order.ts
superfrete/actions/create-shipping.ts
superfrete/actions/generate-label.ts
superfrete/actions/print-label.ts
superfrete/client.ts
superfrete/loaders/addresses.ts
superfrete/loaders/freight-quote.ts
superfrete/loaders/order-info.ts
superfrete/loaders/services-info.ts
superfrete/loaders/user-info.ts
superfrete/mod.ts

add @name superfrete

---

superfrete/actions/cancel-order.ts
superfrete/actions/create-shipping.ts
superfrete/actions/generate-label.ts
superfrete/actions/print-label.ts
superfrete/loaders/addresses.ts
superfrete/loaders/freight-quote.ts
superfrete/loaders/order-info.ts
superfrete/loaders/services-info.ts
superfrete/loaders/user-info.ts

translate title

---

airtable/utils/ui-templates/page-generator.ts

feat: add noRedirect parameter in selection page generation

---

airtable/actions/oauth/callback.ts

airtable oauth callback fix

---

airtable/actions/oauth/callback.ts
airtable/utils/ui-templates/page-generator.ts
airtable/utils/ui-templates/selection-page.template.html

Airtable callback fix

---

google-docs/actions/oauth/callback.ts
google-docs/loaders/oauth/whoami.ts
google-docs/manifest.gen.ts
google-docs/mod.ts
google-drive/actions/oauth/callback.ts
google-drive/loaders/oauth/whoami.ts
google-drive/manifest.gen.ts
google-drive/mod.ts
google-youtube/actions/oauth/callback.ts
google-youtube/loaders/oauth/whoami.ts
google-youtube/manifest.gen.ts
google-youtube/mod.ts

add whoami

---

airtable/actions/oauth/callback.ts
airtable/mod.ts

fix: removing continueQueryParam comparison with string true

---

pinecone-assistant/actions/delete.ts
pinecone-assistant/actions/search.ts
pinecone-assistant/actions/upload.ts
pinecone-assistant/loaders/get.ts
pinecone-assistant/loaders/list.ts

- Updated action and loader interfaces to include a Result type with success status and message.
- Changed action titles to uppercase for consistency.
- Improved error handling in upload and get loaders.
- Updated metadata handling in upload action to support object format.

refactor: enhance file management actions and loaders

---

github/loaders/getPullRequest.ts
github/loaders/getPullRequestDiff.ts
github/loaders/listRepoIssuesRaw.ts
github/manifest.gen.ts
github/utils/client.ts
google-calendar/actions/events/create.ts
google-calendar/actions/events/delete.ts
google-calendar/actions/events/move.ts
google-calendar/actions/events/quickAdd.ts
google-calendar/actions/events/update.ts
google-calendar/loaders/calendars/get.ts
google-calendar/loaders/events/freeBusy.ts
google-calendar/loaders/events/get.ts
google-calendar/loaders/events/instances.ts
google-calendar/loaders/events/list.ts
google-calendar/utils/client.ts
google-calendar/utils/types.ts

- List Issues Raw (without filters in the current List Issues)
- Get Pull Request
- Get Pull Request diff

Adding new Github tools

---

ra-trustvox/sections/TrustvoxProductReviews.tsx

Bom dia,
Neste PR a solução visa corrigir um bug ao tentar adicionar o loader de page na section "TrustvoxProductReviews.tsx"
Veja antes da modificação.
Veja após modificação.
Att,
**Jonathan Lopes.**

fix: update loader function to include props in context on trustvox product reviews

---

airtable/utils/ui-templates/selection-page.template.html
analytics/loaders/OneDollarScript.ts
google-calendar/actions/events/create.ts
google-calendar/actions/events/quickAdd.ts
pinecone-assistant/actions/search.ts
pncp/manifest.gen.ts
slack/actions/deco-chat/channels/invoke.ts
slack/loaders/deco-chat/channels/list.ts
website/components/OneDollarStats.tsx
website/loaders/analyticsScript.ts
website/manifest.gen.ts
website/pages/Page.tsx

Update DEFAULT_COLLECTOR_ADDRESS.
Add static script instead of inline javascript.
TODO on CDN: cache the proxy.

update onedollar stats script

---

airtable/utils/ui-templates/selection-page.template.html
google-gmail/mod.ts
mcp/utils/refresh.ts
mcp/utils/types.ts

fix: Improving the client for refresh tokens and removing constant texts

---

discord-bot/mod.ts
discord-user/mod.ts

feat: add app name on discord

---

clearsale/actions/createFraudScore.ts
clearsale/loaders/getFraudScore.ts

arrays are not supported by mcp

fix: clearsale integration

---

figma/loaders/getImagesToFills.ts
vtex/mod.ts

check and add https://

---

website/loaders/analyticsScript.ts

fix(analytics): drop proxy

---

website/loaders/fonts/googleFonts.ts

Fixes:
```
Error fetching font: https://fonts.googleapis.com/css2?display=swap -  headers: [object Object] - error: HttpError 400: <!DOCTYPE html><html lang=en><head><script>window['ppConfig'] = {productName: 'bcfae741e379a885f2ab2cf83ebe6d32', deleteIsEnforced:  false , sealIsEnforced:  false , heartbeatRate:  0.5 , periodicReportingRateMillis:  60000.0 , disableAllReporting:  false };(function(){'use strict';function k(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var l=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function m(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof …
```

Do not try to render empty fonts, google explodes

---

data-for-seo/mod.ts

fix: remove name in mod.ts
